/// Harbor: ROHD extensions for physical implementation: ASIC tapeout
/// flows, FPGA build support, and reusable SoC components.
///
/// Harbor provides a composable, declarative framework for building
/// RISC-V SoCs using ROHD and rohd_bridge.
library;

// HarborFiber primitives
export 'src/fiber/database.dart';
export 'src/fiber/fiber.dart';
export 'src/fiber/handle.dart';
export 'src/fiber/lock.dart';
export 'src/fiber/retainer.dart';

// Plugin system
export 'src/plugin/plugin.dart';

// HarborPipeline
export 'src/pipeline/builder.dart';
export 'src/pipeline/link.dart';
export 'src/pipeline/node.dart';
export 'src/pipeline/payload.dart';
export 'src/pipeline/stage.dart';

// Bus
export 'src/bus/bus_exports.dart';
export 'src/bus/fabric.dart';

// Cache
export 'src/cache/cache_config.dart';
export 'src/cache/cache_hierarchy.dart';
export 'src/cache/l1_cache.dart';
export 'src/cache/l2_cache.dart';

// Memory
export 'src/memory/data_port.dart';
export 'src/memory/memory_map.dart';
export 'src/memory/memory_port.dart';
export 'src/memory/mmu_config.dart';
export 'src/memory/page_table_walker.dart';
export 'src/memory/pma_checker.dart';
export 'src/memory/tlb.dart';

// Clock
export 'src/clock/cdc.dart';
export 'src/clock/clock_domain.dart';
export 'src/clock/clock_gate.dart';
export 'src/clock/wishbone_cdc.dart';

// SoC
export 'src/soc/acpi.dart';
export 'src/soc/board.dart';
export 'src/soc/boot_sequencer.dart';
export 'src/soc/cpu.dart';
export 'src/soc/device_tree.dart';
export 'src/soc/graph.dart';
export 'src/soc/harbor_soc.dart';
export 'src/soc/interrupt_routing.dart';
export 'src/soc/power_domain.dart';
export 'src/soc/svd.dart';
export 'src/soc/target.dart';

// Video
export 'src/video/display_output.dart';
export 'src/video/double_buffer_scanout.dart';
export 'src/video/double_line_buffer.dart';
export 'src/video/dual_clock_display.dart';
export 'src/video/dual_clock_scanout.dart';
export 'src/video/dvi_output.dart';
export 'src/video/line_fetcher.dart';
export 'src/video/read_arbiter.dart';
export 'src/video/video_capture.dart';
export 'src/video/dvi_transmitter.dart';
export 'src/video/framebuffer_display.dart';
export 'src/video/scanline_dma.dart';
export 'src/video/tmds_encoder.dart';
export 'src/video/tmds_serializer.dart';
export 'src/video/video_timing.dart';

// PDK
export 'src/pdk/analog_block.dart';
export 'src/pdk/gf180mcu.dart';
export 'src/pdk/io_ring.dart';
export 'src/pdk/klayout.dart';
export 'src/pdk/pdk_provider.dart';
export 'src/pdk/sky130.dart';
export 'src/pdk/standard_cell_library.dart';

// RISC-V ISA
export 'src/riscv/decoder.dart';
export 'src/riscv/extension.dart';
export 'src/riscv/isa.dart';
export 'src/riscv/micro_op.dart';
export 'src/riscv/mxlen.dart';
export 'src/riscv/operation.dart';
export 'src/riscv/paging.dart';
export 'src/riscv/resource.dart';
export 'src/riscv/extensions/rv32i.dart';
export 'src/riscv/extensions/rv64i.dart';
export 'src/riscv/extensions/rv_a.dart';
export 'src/riscv/extensions/rv_b.dart';
export 'src/riscv/extensions/rv_c.dart';
export 'src/riscv/extensions/rv_d.dart';
export 'src/riscv/extensions/rv_f.dart';
export 'src/riscv/extensions/rv_h.dart';
export 'src/riscv/extensions/rv_m.dart';
export 'src/riscv/extensions/rv_priv.dart';
export 'src/riscv/extensions/rv_misc.dart';
export 'src/riscv/extensions/rv_zfhmin.dart';
export 'src/riscv/extensions/rv_zicond.dart';
export 'src/riscv/profiles/rva23.dart';
export 'src/riscv/extensions/rv_v.dart';
export 'src/riscv/extensions/rv_zicsr.dart';
export 'src/riscv/extensions/rv_zifencei.dart';

// Blackbox (FPGA primitives)
export 'src/blackbox/ice40/ice40.dart';
export 'src/blackbox/ecp5/ecp5.dart';
export 'src/blackbox/xilinx/xilinx.dart';
export 'src/blackbox/xilinx/iserdese2_sim.dart';
export 'src/blackbox/xilinx/oserdese2_sim.dart';

// Encoding
export 'src/encoding/bit_struct.dart';
export 'src/encoding/riscv_compressed.dart';
export 'src/encoding/riscv_csr.dart';
export 'src/encoding/riscv_formats.dart';
export 'src/encoding/riscv_hypervisor.dart';
export 'src/encoding/riscv_vector.dart';
export 'src/encoding/rvc_immediate.dart';

// Media
export 'src/media/audio.dart';
export 'src/media/bit_reader.dart';
export 'src/media/block_attributes.dart';
export 'src/media/codec.dart';
export 'src/media/coeff_context.dart';
export 'src/media/compound_blend.dart';
export 'src/media/coeff_ctx_decoder.dart';
export 'src/media/coeff_levels.dart';
export 'src/media/cdef_block.dart';
export 'src/media/cdef_direction.dart';
export 'src/media/cdef_filter_sentinel.dart';
export 'src/media/cdef_frame.dart';
export 'src/media/cdef_frame_pass.dart';
export 'src/media/cdef_filter.dart';
export 'src/media/cdef_params_parser.dart';
export 'src/media/cfl_alpha_decode.dart';
export 'src/media/cfl_predict.dart';
export 'src/media/chroma_recon_block.dart';
export 'src/media/coeff_decoder.dart';
export 'src/media/color_config_parser.dart';
export 'src/media/deblock4.dart';
export 'src/media/deblock6.dart';
export 'src/media/deblock8.dart';
export 'src/media/deblock14.dart';
export 'src/media/deblock_edge.dart';
export 'src/media/deblock_edge_select.dart';
export 'src/media/deblock_filter.dart';
export 'src/media/deblock_frame.dart';
export 'src/media/deblock_frame_pass.dart';
export 'src/media/deblock_luma_frame.dart';
export 'src/media/deblock_thresh.dart';
export 'src/media/dpb.dart';
export 'src/media/decode_frame_intra.dart';
export 'src/media/decode_row_intra.dart';
export 'src/media/decode_tile.dart';
export 'src/media/delta_params_parser.dart';
export 'src/media/dequant.dart';
export 'src/media/film_grain_apply.dart';
export 'src/media/film_grain_scale.dart';
export 'src/media/film_grain_synth.dart';
export 'src/media/filter_config_parser.dart';
export 'src/media/filter_intra.dart';
export 'src/media/deblock_limits.dart';
export 'src/media/eob_decode.dart';
export 'src/media/frame_deblock.dart';
export 'src/media/frame_header_parse.dart';
export 'src/media/frame_size_parser.dart';
export 'src/media/global_mv.dart';
export 'src/media/global_warp_model.dart';
export 'src/media/gm_params.dart';
export 'src/media/golomb_reader.dart';
export 'src/media/entropy_decoder.dart';
export 'src/media/inter_convolve.dart';
export 'src/media/inter_convolve_d16.dart';
export 'src/media/inter_predictor.dart';
export 'src/media/inter_scale_setup.dart';
export 'src/media/inv_txfm.dart';
export 'src/media/inv_txfm_4x4.dart';
export 'src/media/inverse_dct4.dart';
export 'src/media/inverse_dct8.dart';
export 'src/media/intra_angle.dart';
export 'src/media/intra_block_decode.dart';
export 'src/media/intra_decoder.dart';
export 'src/media/intra_frame_header.dart';
export 'src/media/intra_line_buffer.dart';
export 'src/media/intra_mode_info.dart';
export 'src/media/intra_mode_pred.dart';
export 'src/media/intra_pred_avail.dart';
export 'src/media/intra_pred_full.dart';
export 'src/media/intra_mode_tx_type.dart';
export 'src/media/keyframe_decode.dart';
export 'src/media/keyframe_decode_var.dart';
export 'src/media/keyframe_decode_root16.dart';
export 'src/media/keyframe_decode_root32.dart';
export 'src/media/keyframe_decode_sb32.dart';
export 'src/media/keyframe_decode_root64.dart';
export 'src/media/keyframe_decode_2sb16_seq.dart';
export 'src/media/keyframe_decode_2sb16_vert_seq.dart';
export 'src/media/keyframe_decode_tile16_seq.dart';
export 'src/media/keyframe_decode_multisb_horiz.dart';
export 'src/media/keyframe_decode_multisb_vert.dart';
export 'src/media/keyframe_decode_tile.dart';
export 'src/media/keyframe_decode_tile_yuv.dart';
export 'src/media/keyframe_decode_tile_yuv_vert.dart';
export 'src/media/keyframe_decode_tile_yuv_2x2.dart';
export 'src/media/keyframe_decode_tile_yuv_tile.dart';
export 'src/media/keyframe_decode_tile2x2.dart';
export 'src/media/keyframe_decode_horzvert.dart';
export 'src/media/keyframe_decode_horzvert_yuv.dart';
export 'src/media/keyframe_decode_yuv.dart';
export 'src/media/keyframe_decode_yuv16.dart';
export 'src/media/keyframe_decode_yuv_var.dart';
export 'src/media/keyframe_mode_walk.dart';
export 'src/media/inter_frame_walk.dart';
export 'src/media/inter_mode_walk.dart';
export 'src/media/keyframe_recon_grid.dart';
export 'src/media/kf_ymode_context.dart';
export 'src/media/kf_ymode_decode.dart';
export 'src/media/motion_field.dart';
export 'src/media/mv_projection.dart';
export 'src/media/ns_reader.dart';
export 'src/media/store_frame_mvs.dart';
export 'src/media/obu_front_end.dart';
export 'src/media/obu_parser.dart';
export 'src/media/obu_stream_walker.dart';
export 'src/media/od_ec_decoder.dart';
export 'src/media/partition_context.dart';
export 'src/media/partition_decode.dart';
export 'src/media/partition_subsize.dart';
export 'src/media/partition_symbol.dart';
export 'src/media/partition_tree.dart';
export 'src/media/partition_tree_walk.dart';
export 'src/media/recon_add.dart';
export 'src/media/palette_recon.dart';
export 'src/media/palette_color_context.dart';
export 'src/media/intra_dir.dart';
export 'src/media/intra_edge.dart';
export 'src/media/intra_pred_rect.dart';
export 'src/media/intra_recon_walk.dart';
export 'src/media/intra_pred_row.dart';
export 'src/media/intra_recon_block_seq.dart';
export 'src/media/intra_recon_walk_seq.dart';
export 'src/media/intra_dir_angle.dart';
export 'src/media/intra_dir_edge.dart';
export 'src/media/intra_pred.dart';
export 'src/media/intra_predictor.dart';
export 'src/media/loop_filter_params_parser.dart';
export 'src/media/lr_frame.dart';
export 'src/media/lr_frame_walk.dart';
export 'src/media/lr_params_parser.dart';
export 'src/media/lr_unit.dart';
export 'src/media/mask_blend.dart';
export 'src/media/max_tx_size.dart';
export 'src/media/media_engine.dart';
export 'src/media/quant_lookup.dart';
export 'src/media/quant_params_parser.dart';
export 'src/media/reconstruct4.dart';
export 'src/media/reconstruct8.dart';
export 'src/media/render_size_parser.dart';
export 'src/media/uv_mode_decode.dart';
export 'src/media/uvlc_reader.dart';
export 'src/media/sb_walk.dart';
export 'src/media/scan_order.dart';
export 'src/media/sgr_block.dart';
export 'src/media/sgr_boxsum.dart';
export 'src/media/sgr_calc_ab.dart';
export 'src/media/sgr_cross_sum.dart';
export 'src/media/sgr_filter.dart';
export 'src/media/sgr_pass.dart';
export 'src/media/sgr_proc_unit.dart';
export 'src/media/seq_header_parse.dart';
export 'src/media/seq_header_parser.dart';
export 'src/media/segmentation_params_parser.dart';
export 'src/media/sgr_project.dart';
export 'src/media/su_reader.dart';
export 'src/media/tile_decode_driver.dart';
export 'src/media/tile_group_parse.dart';
export 'src/media/tile_info_parser.dart';
export 'src/media/tx_mode_parser.dart';
export 'src/media/tx_size_decode.dart';
export 'src/media/tx_size_geom.dart';
export 'src/media/tx_size_sqr.dart';
export 'src/media/tx_type_read.dart';
export 'src/media/warp_affine.dart';
export 'src/media/warp_estimate.dart';
export 'src/media/wedge_mask.dart';
export 'src/media/wiener_filter.dart';

// Debug / JTAG
export 'src/debug/debug_module.dart';
export 'src/debug/debug_transport.dart';
export 'src/debug/jtag_interface.dart';
export 'src/debug/jtag_remote.dart';
export 'src/debug/jtag_tap.dart';
export 'src/debug/trace.dart';

// Utilities
export 'src/util/elf_loader.dart';
export 'src/util/pretty_string.dart';

// OpenSBI
export 'src/opensbi/platform.dart';

// Peripherals
export 'src/peripherals/aplic.dart';
export 'src/peripherals/bram.dart';
export 'src/peripherals/clint.dart';
export 'src/peripherals/crypto.dart';
export 'src/peripherals/ddr.dart';
export 'src/peripherals/ddr_read_assembler.dart';
export 'src/peripherals/ddr_xilinx_read_train.dart';
export 'src/peripherals/device_register.dart';
export 'src/peripherals/ecp5_delay_controller.dart';
export 'src/peripherals/display.dart';
export 'src/peripherals/dma.dart';
export 'src/peripherals/efuse.dart';
export 'src/peripherals/trng.dart';
export 'src/peripherals/ethernet.dart';
export 'src/peripherals/flash.dart';
export 'src/peripherals/gpio.dart';
export 'src/peripherals/hpm.dart';
export 'src/peripherals/i2c.dart';
export 'src/peripherals/imsic.dart';
export 'src/peripherals/iommu.dart';
export 'src/peripherals/maskrom.dart';
export 'src/peripherals/pcie.dart';
export 'src/peripherals/plic.dart';
export 'src/peripherals/pmu.dart';
export 'src/peripherals/psram.dart';
export 'src/peripherals/pwm_timer.dart';
export 'src/peripherals/register_file.dart';
export 'src/peripherals/reset_controller.dart';
export 'src/peripherals/sdio.dart';
export 'src/peripherals/spi.dart';
export 'src/peripherals/spi_flash.dart';
export 'src/peripherals/sram.dart';
export 'src/peripherals/temperature_sensor.dart';
export 'src/peripherals/uart.dart';
export 'src/peripherals/usb.dart';
export 'src/peripherals/usb_dfu.dart';
export 'src/peripherals/usb_phy.dart';
export 'src/peripherals/watchdog.dart';
