import 'package:rohd/rohd.dart';

import '../blackbox/ecp5/ecp5.dart';
import '../blackbox/xilinx/xilinx.dart';
import '../soc/target.dart';
import 'ddr_output.dart';

/// Serializes a 10-bit TMDS symbol onto one ECP5 output, LSB first.
///
/// Runs in the shift-clock domain (5x the pixel clock). A mod-5 gearbox shifts
/// the symbol out two bits per cycle as a DDR pair ([d0] on the rising edge,
/// [d1] on the falling edge), feeding an `ODDRX1F` so the pin toggles at 10x
/// the pixel clock across the ten symbol bits. The 10-bit [symbol] is in the
/// pixel-clock domain and is reloaded once per five shift cycles.
///
/// [q] is the serialized pin output (drive the GPDI true pin, IO type
/// `LVCMOS33D`, and the complement pad is generated by the tool). [d0]/[d1] are
/// the gearbox DDR pair, exposed for verification.
class TmdsSerializer extends Module {
  /// True whether [target] wants the complement lane driven by the design.
  ///
  /// Lattice makes the complement in the pad, from one `LVCMOS33D` site, so the
  /// design drives one pin per lane. Xilinx has no such site in the open flow,
  /// so a passive TMDS adapter needs both pins driven as plain `LVCMOS33`, and
  /// [qn] carries the second one.
  static bool needsComplement(HarborDeviceTarget target) =>
      target is HarborFpgaTarget &&
      (target.vendor == HarborFpgaVendor.vivado ||
          target.vendor == HarborFpgaVendor.openXc7);

  /// Serialized pin output (through the ODDR).
  Logic get q => output('q');

  /// The complement lane, present only when [needsComplement] is true.
  ///
  /// It comes out of its OWN output register, fed inverted data. Inverting [q]
  /// with a gate instead would put the complement one gate delay behind the
  /// true lane, and a TMDS receiver reads the difference between the two.
  Logic get qn => output('qn');

  /// DDR bit pair feeding the output register (rising-edge / falling-edge bit).
  Logic get d0 => output('d0');
  Logic get d1 => output('d1');

  TmdsSerializer({
    required Logic shiftClk,
    required Logic reset,
    required Logic symbol,
    required HarborDeviceTarget target,
    super.name = 'tmds_serializer',
  }) : super(definitionName: 'TmdsSerializer') {
    shiftClk = addInput('shift_clk', shiftClk);
    reset = addInput('reset', reset);
    symbol = addInput('symbol', symbol, width: 10);
    addOutput('d0');
    addOutput('d1');
    addOutput('q');
    if (needsComplement(target)) {
      addOutput('qn');
    }

    // mod-5 phase and the 10-bit shift register, in the shift-clock domain.
    final phase = Logic(name: 'phase', width: 3);
    final sr = Logic(name: 'shift_reg', width: 10);

    Sequential(shiftClk, reset: reset, [
      If(
        phase.eq(4),
        then: [
          phase < 0,
          sr < symbol, // reload at the start of the next word
        ],
        orElse: [
          phase < phase + 1,
          sr < (sr >> 2), // emit two bits per cycle, LSB first
        ],
      ),
    ]);

    d0 <= sr[0];
    d1 <= sr[1];

    // The gearbox above is family-independent. Only the output register is a
    // hard primitive, so it is the one part that changes with the target.
    //
    // Both primitives have the same 1:2 meaning: the first bit goes out while
    // the shift clock is high and the second while it is low. On the Xilinx
    // part, DDR_CLK_EDGE "SAME_EDGE" gives that, because it presents both bits
    // on the same rising edge.
    //
    // A simulation build uses neither. Both hard cells are black boxes with no
    // body, so a simulation cannot run them, and standing one vendor's cell in
    // for another's would put a cell in the netlist that the part does not
    // have. [HarborDdrOutput] is the same gearing in plain logic.
    q <=
        switch (target) {
          HarborSimTarget() => HarborDdrOutput(
            clk: shiftClk,
            reset: reset,
            d0: sr[0],
            d1: sr[1],
          ).q,
          HarborFpgaTarget(vendor: HarborFpgaVendor.ecp5) => Ecp5Oddrx1f(
            sclk: shiftClk,
            rst: reset,
            d0: sr[0],
            d1: sr[1],
          ).q,
          HarborFpgaTarget(vendor: HarborFpgaVendor.vivado) ||
          HarborFpgaTarget(
            vendor: HarborFpgaVendor.openXc7,
          ) => XilinxOddr(c: shiftClk, d1: sr[0], d2: sr[1], r: reset).q,
          HarborFpgaTarget(vendor: HarborFpgaVendor.ice40) => throw UnsupportedError(
            'TmdsSerializer has no output register for iCE40: the family has no '
            'DDR output primitive in this catalog, and TMDS needs one to reach 10x '
            'the pixel clock. Use an ECP5 or a Xilinx 7-series part for a display.',
          ),
          HarborAsicTarget() => throw UnsupportedError(
            'TmdsSerializer has no output register for an ASIC target: a DDR pad '
            'is process specific and comes from the foundry IO library.',
          ),
        };

    if (needsComplement(target)) {
      qn <=
          XilinxOddr(
            c: shiftClk,
            d1: ~sr[0],
            d2: ~sr[1],
            r: reset,
            name: 'oddr_n',
          ).q;
    }
  }
}
