import 'package:rohd/rohd.dart';

import '../blackbox/ecp5/ecp5.dart';

/// Serializes a 10-bit TMDS symbol onto one ECP5 output, LSB first.
///
/// Runs in the shift-clock domain (5x the pixel clock). A mod-5 gearbox shifts
/// the symbol out two bits per cycle as a DDR pair ([d0] on the rising edge,
/// [d1] on the falling edge), feeding an `ODDRX1F` so the pin toggles at 10x
/// the pixel clock across the ten symbol bits. The 10-bit [symbol] is in the
/// pixel-clock domain and is reloaded once per five shift cycles.
///
/// [q] is the serialized pin output (drive the GPDI true pin, IO type
/// `LVCMOS33D`, and the complement pad is generated by the tool). [d0]/[d1] are
/// the gearbox DDR pair, exposed for verification.
class TmdsSerializer extends Module {
  /// Serialized pin output (through the ODDR).
  Logic get q => output('q');

  /// DDR bit pair feeding the output register (rising-edge / falling-edge bit).
  Logic get d0 => output('d0');
  Logic get d1 => output('d1');

  TmdsSerializer({
    required Logic shiftClk,
    required Logic reset,
    required Logic symbol,
    super.name = 'tmds_serializer',
  }) : super(definitionName: 'TmdsSerializer') {
    shiftClk = addInput('shift_clk', shiftClk);
    reset = addInput('reset', reset);
    symbol = addInput('symbol', symbol, width: 10);
    addOutput('d0');
    addOutput('d1');
    addOutput('q');

    // mod-5 phase and the 10-bit shift register, in the shift-clock domain.
    final phase = Logic(name: 'phase', width: 3);
    final sr = Logic(name: 'shift_reg', width: 10);

    Sequential(shiftClk, reset: reset, [
      If(
        phase.eq(4),
        then: [
          phase < 0,
          sr < symbol, // reload at the start of the next word
        ],
        orElse: [
          phase < phase + 1,
          sr < (sr >> 2), // emit two bits per cycle, LSB first
        ],
      ),
    ]);

    d0 <= sr[0];
    d1 <= sr[1];

    // ODDRX1F: D0 on the rising edge of SCLK, D1 on the falling edge.
    final oddr = Ecp5Oddrx1f(sclk: shiftClk, rst: reset, d0: sr[0], d1: sr[1]);
    q <= oddr.q;
  }
}
