import 'dart:async';
import 'dart:math';

import 'package:harbor/harbor.dart';
import 'package:rohd/rohd.dart';
import 'package:test/test.dart';

// Front-end COMPOSITION: HarborSeqHeaderParse's field outputs are wired DIRECTLY
// into HarborFrameHeaderParse's seq-dependency inputs (same names, minus the
// `seq_` prefix), proving the two bit-exact parsers actually connect. A seq
// header OBU payload and a frame header OBU payload (separate byte windows, as
// real OBUs are) drive the two modules in sequence. The SW reference
// parseSequenceHeader -> parseFrameHeader is the golden.

// Minimal sequence-header holder (only the fields the frame-header writer reads)
// reconstructed from the captured golden, replacing the SW SequenceHeader.
class _Seq {
  int seqForceScreenContentTools = 0;
  int seqForceIntegerMv = 0;
  int orderHintBits = 0;
  int frameWidthBitsMinus1 = 0;
  int frameHeightBitsMinus1 = 0;
  bool enableSuperres = false;
  int numPlanes = 3;
  bool separateUvDeltaQ = false;
  bool enableCdef = false;
  bool enableRestoration = false;
  int subsamplingX = 1;
  int subsamplingY = 1;
  bool filmGrainParamsPresent = false;
}

// Golden seq fields (for the writer) + parsed frame-header fields, captured from
// the SW reference parseSequenceHeader -> parseFrameHeader for each iteration.
typedef _Row = ({
  int seqForceScreenContentTools,
  int seqForceIntegerMv,
  int orderHintBits,
  int frameWidthBitsMinus1,
  int frameHeightBitsMinus1,
  bool enableSuperres,
  int numPlanes,
  bool separateUvDeltaQ,
  bool enableCdef,
  bool enableRestoration,
  int subsamplingX,
  int subsamplingY,
  bool filmGrainParamsPresent,
  bool enableOrderHint,
  bool frameIsIntra,
  bool showFrame,
  bool allowScreenContentTools,
  int forceIntegerMv,
  int orderHint,
  int frameWidth,
  int frameHeight,
  int baseQIdx,
  bool codedLossless,
  int loopFilterLevel0,
  int cdefBits,
  bool usesLr,
  int txMode,
  bool reducedTxSet,
});
const _golden = <_Row>[
  (
    seqForceScreenContentTools: 2,
    seqForceIntegerMv: 1,
    orderHintBits: 4,
    frameWidthBitsMinus1: 6,
    frameHeightBitsMinus1: 4,
    enableSuperres: true,
    numPlanes: 3,
    separateUvDeltaQ: false,
    enableCdef: true,
    enableRestoration: false,
    subsamplingX: 1,
    subsamplingY: 1,
    filmGrainParamsPresent: true,
    enableOrderHint: true,
    frameIsIntra: true,
    showFrame: false,
    allowScreenContentTools: true,
    forceIntegerMv: 1,
    orderHint: 10,
    frameWidth: 21,
    frameHeight: 3,
    baseQIdx: 217,
    codedLossless: false,
    loopFilterLevel0: 61,
    cdefBits: 3,
    usesLr: false,
    txMode: 1,
    reducedTxSet: false,
  ),
  (
    seqForceScreenContentTools: 0,
    seqForceIntegerMv: 2,
    orderHintBits: 2,
    frameWidthBitsMinus1: 3,
    frameHeightBitsMinus1: 4,
    enableSuperres: false,
    numPlanes: 3,
    separateUvDeltaQ: false,
    enableCdef: true,
    enableRestoration: false,
    subsamplingX: 1,
    subsamplingY: 1,
    filmGrainParamsPresent: true,
    enableOrderHint: true,
    frameIsIntra: true,
    showFrame: false,
    allowScreenContentTools: false,
    forceIntegerMv: 1,
    orderHint: 3,
    frameWidth: 13,
    frameHeight: 12,
    baseQIdx: 0,
    codedLossless: true,
    loopFilterLevel0: 0,
    cdefBits: 0,
    usesLr: false,
    txMode: 0,
    reducedTxSet: false,
  ),
  (
    seqForceScreenContentTools: 1,
    seqForceIntegerMv: 2,
    orderHintBits: 0,
    frameWidthBitsMinus1: 5,
    frameHeightBitsMinus1: 6,
    enableSuperres: true,
    numPlanes: 3,
    separateUvDeltaQ: false,
    enableCdef: false,
    enableRestoration: false,
    subsamplingX: 1,
    subsamplingY: 1,
    filmGrainParamsPresent: false,
    enableOrderHint: false,
    frameIsIntra: true,
    showFrame: false,
    allowScreenContentTools: true,
    forceIntegerMv: 1,
    orderHint: 0,
    frameWidth: 11,
    frameHeight: 42,
    baseQIdx: 214,
    codedLossless: false,
    loopFilterLevel0: 0,
    cdefBits: 0,
    usesLr: false,
    txMode: 2,
    reducedTxSet: true,
  ),
  (
    seqForceScreenContentTools: 2,
    seqForceIntegerMv: 2,
    orderHintBits: 8,
    frameWidthBitsMinus1: 4,
    frameHeightBitsMinus1: 6,
    enableSuperres: true,
    numPlanes: 3,
    separateUvDeltaQ: false,
    enableCdef: false,
    enableRestoration: true,
    subsamplingX: 1,
    subsamplingY: 1,
    filmGrainParamsPresent: true,
    enableOrderHint: true,
    frameIsIntra: true,
    showFrame: false,
    allowScreenContentTools: false,
    forceIntegerMv: 1,
    orderHint: 0,
    frameWidth: 15,
    frameHeight: 58,
    baseQIdx: 71,
    codedLossless: false,
    loopFilterLevel0: 12,
    cdefBits: 0,
    usesLr: true,
    txMode: 2,
    reducedTxSet: true,
  ),
  (
    seqForceScreenContentTools: 0,
    seqForceIntegerMv: 2,
    orderHintBits: 0,
    frameWidthBitsMinus1: 5,
    frameHeightBitsMinus1: 6,
    enableSuperres: true,
    numPlanes: 3,
    separateUvDeltaQ: false,
    enableCdef: false,
    enableRestoration: true,
    subsamplingX: 1,
    subsamplingY: 1,
    filmGrainParamsPresent: true,
    enableOrderHint: false,
    frameIsIntra: true,
    showFrame: true,
    allowScreenContentTools: false,
    forceIntegerMv: 1,
    orderHint: 0,
    frameWidth: 14,
    frameHeight: 59,
    baseQIdx: 66,
    codedLossless: false,
    loopFilterLevel0: 25,
    cdefBits: 0,
    usesLr: true,
    txMode: 2,
    reducedTxSet: false,
  ),
  (
    seqForceScreenContentTools: 2,
    seqForceIntegerMv: 0,
    orderHintBits: 3,
    frameWidthBitsMinus1: 6,
    frameHeightBitsMinus1: 6,
    enableSuperres: true,
    numPlanes: 3,
    separateUvDeltaQ: false,
    enableCdef: false,
    enableRestoration: true,
    subsamplingX: 1,
    subsamplingY: 1,
    filmGrainParamsPresent: false,
    enableOrderHint: true,
    frameIsIntra: true,
    showFrame: true,
    allowScreenContentTools: false,
    forceIntegerMv: 1,
    orderHint: 0,
    frameWidth: 24,
    frameHeight: 22,
    baseQIdx: 234,
    codedLossless: false,
    loopFilterLevel0: 31,
    cdefBits: 0,
    usesLr: true,
    txMode: 1,
    reducedTxSet: true,
  ),
  (
    seqForceScreenContentTools: 1,
    seqForceIntegerMv: 1,
    orderHintBits: 0,
    frameWidthBitsMinus1: 3,
    frameHeightBitsMinus1: 4,
    enableSuperres: true,
    numPlanes: 3,
    separateUvDeltaQ: false,
    enableCdef: false,
    enableRestoration: true,
    subsamplingX: 1,
    subsamplingY: 1,
    filmGrainParamsPresent: true,
    enableOrderHint: false,
    frameIsIntra: true,
    showFrame: false,
    allowScreenContentTools: true,
    forceIntegerMv: 1,
    orderHint: 0,
    frameWidth: 5,
    frameHeight: 9,
    baseQIdx: 92,
    codedLossless: false,
    loopFilterLevel0: 8,
    cdefBits: 0,
    usesLr: true,
    txMode: 2,
    reducedTxSet: true,
  ),
  (
    seqForceScreenContentTools: 1,
    seqForceIntegerMv: 2,
    orderHintBits: 0,
    frameWidthBitsMinus1: 3,
    frameHeightBitsMinus1: 5,
    enableSuperres: true,
    numPlanes: 3,
    separateUvDeltaQ: false,
    enableCdef: true,
    enableRestoration: true,
    subsamplingX: 1,
    subsamplingY: 1,
    filmGrainParamsPresent: false,
    enableOrderHint: false,
    frameIsIntra: true,
    showFrame: true,
    allowScreenContentTools: true,
    forceIntegerMv: 1,
    orderHint: 0,
    frameWidth: 7,
    frameHeight: 48,
    baseQIdx: 163,
    codedLossless: false,
    loopFilterLevel0: 0,
    cdefBits: 0,
    usesLr: false,
    txMode: 2,
    reducedTxSet: false,
  ),
  (
    seqForceScreenContentTools: 0,
    seqForceIntegerMv: 2,
    orderHintBits: 0,
    frameWidthBitsMinus1: 3,
    frameHeightBitsMinus1: 4,
    enableSuperres: true,
    numPlanes: 3,
    separateUvDeltaQ: true,
    enableCdef: true,
    enableRestoration: true,
    subsamplingX: 1,
    subsamplingY: 1,
    filmGrainParamsPresent: false,
    enableOrderHint: false,
    frameIsIntra: true,
    showFrame: false,
    allowScreenContentTools: false,
    forceIntegerMv: 1,
    orderHint: 0,
    frameWidth: 16,
    frameHeight: 25,
    baseQIdx: 174,
    codedLossless: false,
    loopFilterLevel0: 27,
    cdefBits: 0,
    usesLr: true,
    txMode: 1,
    reducedTxSet: false,
  ),
  (
    seqForceScreenContentTools: 2,
    seqForceIntegerMv: 1,
    orderHintBits: 0,
    frameWidthBitsMinus1: 5,
    frameHeightBitsMinus1: 3,
    enableSuperres: false,
    numPlanes: 3,
    separateUvDeltaQ: true,
    enableCdef: false,
    enableRestoration: true,
    subsamplingX: 1,
    subsamplingY: 1,
    filmGrainParamsPresent: true,
    enableOrderHint: false,
    frameIsIntra: true,
    showFrame: true,
    allowScreenContentTools: false,
    forceIntegerMv: 1,
    orderHint: 0,
    frameWidth: 16,
    frameHeight: 13,
    baseQIdx: 120,
    codedLossless: false,
    loopFilterLevel0: 32,
    cdefBits: 0,
    usesLr: true,
    txMode: 2,
    reducedTxSet: true,
  ),
  (
    seqForceScreenContentTools: 2,
    seqForceIntegerMv: 2,
    orderHintBits: 1,
    frameWidthBitsMinus1: 5,
    frameHeightBitsMinus1: 6,
    enableSuperres: false,
    numPlanes: 3,
    separateUvDeltaQ: true,
    enableCdef: false,
    enableRestoration: false,
    subsamplingX: 1,
    subsamplingY: 1,
    filmGrainParamsPresent: false,
    enableOrderHint: true,
    frameIsIntra: true,
    showFrame: true,
    allowScreenContentTools: false,
    forceIntegerMv: 1,
    orderHint: 1,
    frameWidth: 11,
    frameHeight: 5,
    baseQIdx: 172,
    codedLossless: false,
    loopFilterLevel0: 14,
    cdefBits: 0,
    usesLr: false,
    txMode: 1,
    reducedTxSet: true,
  ),
  (
    seqForceScreenContentTools: 2,
    seqForceIntegerMv: 2,
    orderHintBits: 0,
    frameWidthBitsMinus1: 6,
    frameHeightBitsMinus1: 6,
    enableSuperres: false,
    numPlanes: 3,
    separateUvDeltaQ: true,
    enableCdef: false,
    enableRestoration: false,
    subsamplingX: 1,
    subsamplingY: 1,
    filmGrainParamsPresent: false,
    enableOrderHint: false,
    frameIsIntra: true,
    showFrame: true,
    allowScreenContentTools: true,
    forceIntegerMv: 1,
    orderHint: 0,
    frameWidth: 55,
    frameHeight: 19,
    baseQIdx: 25,
    codedLossless: false,
    loopFilterLevel0: 8,
    cdefBits: 0,
    usesLr: false,
    txMode: 1,
    reducedTxSet: true,
  ),
  (
    seqForceScreenContentTools: 1,
    seqForceIntegerMv: 2,
    orderHintBits: 7,
    frameWidthBitsMinus1: 5,
    frameHeightBitsMinus1: 4,
    enableSuperres: false,
    numPlanes: 3,
    separateUvDeltaQ: false,
    enableCdef: false,
    enableRestoration: true,
    subsamplingX: 1,
    subsamplingY: 1,
    filmGrainParamsPresent: false,
    enableOrderHint: true,
    frameIsIntra: true,
    showFrame: false,
    allowScreenContentTools: true,
    forceIntegerMv: 1,
    orderHint: 26,
    frameWidth: 12,
    frameHeight: 17,
    baseQIdx: 1,
    codedLossless: false,
    loopFilterLevel0: 0,
    cdefBits: 0,
    usesLr: true,
    txMode: 2,
    reducedTxSet: false,
  ),
  (
    seqForceScreenContentTools: 2,
    seqForceIntegerMv: 2,
    orderHintBits: 0,
    frameWidthBitsMinus1: 3,
    frameHeightBitsMinus1: 5,
    enableSuperres: true,
    numPlanes: 3,
    separateUvDeltaQ: false,
    enableCdef: true,
    enableRestoration: false,
    subsamplingX: 1,
    subsamplingY: 1,
    filmGrainParamsPresent: true,
    enableOrderHint: false,
    frameIsIntra: true,
    showFrame: false,
    allowScreenContentTools: true,
    forceIntegerMv: 1,
    orderHint: 0,
    frameWidth: 13,
    frameHeight: 27,
    baseQIdx: 230,
    codedLossless: false,
    loopFilterLevel0: 0,
    cdefBits: 0,
    usesLr: false,
    txMode: 1,
    reducedTxSet: false,
  ),
  (
    seqForceScreenContentTools: 0,
    seqForceIntegerMv: 2,
    orderHintBits: 0,
    frameWidthBitsMinus1: 6,
    frameHeightBitsMinus1: 3,
    enableSuperres: true,
    numPlanes: 3,
    separateUvDeltaQ: false,
    enableCdef: false,
    enableRestoration: true,
    subsamplingX: 1,
    subsamplingY: 1,
    filmGrainParamsPresent: false,
    enableOrderHint: false,
    frameIsIntra: true,
    showFrame: true,
    allowScreenContentTools: false,
    forceIntegerMv: 1,
    orderHint: 0,
    frameWidth: 62,
    frameHeight: 5,
    baseQIdx: 31,
    codedLossless: false,
    loopFilterLevel0: 14,
    cdefBits: 0,
    usesLr: true,
    txMode: 1,
    reducedTxSet: true,
  ),
  (
    seqForceScreenContentTools: 1,
    seqForceIntegerMv: 2,
    orderHintBits: 7,
    frameWidthBitsMinus1: 5,
    frameHeightBitsMinus1: 3,
    enableSuperres: true,
    numPlanes: 3,
    separateUvDeltaQ: false,
    enableCdef: false,
    enableRestoration: true,
    subsamplingX: 1,
    subsamplingY: 1,
    filmGrainParamsPresent: false,
    enableOrderHint: true,
    frameIsIntra: true,
    showFrame: true,
    allowScreenContentTools: true,
    forceIntegerMv: 1,
    orderHint: 12,
    frameWidth: 63,
    frameHeight: 16,
    baseQIdx: 31,
    codedLossless: false,
    loopFilterLevel0: 0,
    cdefBits: 0,
    usesLr: false,
    txMode: 1,
    reducedTxSet: false,
  ),
  (
    seqForceScreenContentTools: 2,
    seqForceIntegerMv: 1,
    orderHintBits: 8,
    frameWidthBitsMinus1: 4,
    frameHeightBitsMinus1: 5,
    enableSuperres: false,
    numPlanes: 3,
    separateUvDeltaQ: false,
    enableCdef: false,
    enableRestoration: true,
    subsamplingX: 1,
    subsamplingY: 1,
    filmGrainParamsPresent: true,
    enableOrderHint: true,
    frameIsIntra: true,
    showFrame: true,
    allowScreenContentTools: true,
    forceIntegerMv: 1,
    orderHint: 28,
    frameWidth: 11,
    frameHeight: 14,
    baseQIdx: 163,
    codedLossless: false,
    loopFilterLevel0: 0,
    cdefBits: 0,
    usesLr: false,
    txMode: 2,
    reducedTxSet: true,
  ),
  (
    seqForceScreenContentTools: 2,
    seqForceIntegerMv: 1,
    orderHintBits: 0,
    frameWidthBitsMinus1: 4,
    frameHeightBitsMinus1: 6,
    enableSuperres: false,
    numPlanes: 3,
    separateUvDeltaQ: true,
    enableCdef: false,
    enableRestoration: true,
    subsamplingX: 1,
    subsamplingY: 1,
    filmGrainParamsPresent: false,
    enableOrderHint: false,
    frameIsIntra: true,
    showFrame: false,
    allowScreenContentTools: false,
    forceIntegerMv: 1,
    orderHint: 0,
    frameWidth: 31,
    frameHeight: 53,
    baseQIdx: 96,
    codedLossless: false,
    loopFilterLevel0: 25,
    cdefBits: 0,
    usesLr: true,
    txMode: 1,
    reducedTxSet: false,
  ),
  (
    seqForceScreenContentTools: 0,
    seqForceIntegerMv: 2,
    orderHintBits: 0,
    frameWidthBitsMinus1: 4,
    frameHeightBitsMinus1: 5,
    enableSuperres: false,
    numPlanes: 3,
    separateUvDeltaQ: true,
    enableCdef: false,
    enableRestoration: true,
    subsamplingX: 1,
    subsamplingY: 1,
    filmGrainParamsPresent: false,
    enableOrderHint: false,
    frameIsIntra: true,
    showFrame: true,
    allowScreenContentTools: false,
    forceIntegerMv: 1,
    orderHint: 0,
    frameWidth: 3,
    frameHeight: 62,
    baseQIdx: 139,
    codedLossless: false,
    loopFilterLevel0: 27,
    cdefBits: 0,
    usesLr: true,
    txMode: 1,
    reducedTxSet: false,
  ),
  (
    seqForceScreenContentTools: 1,
    seqForceIntegerMv: 2,
    orderHintBits: 4,
    frameWidthBitsMinus1: 6,
    frameHeightBitsMinus1: 3,
    enableSuperres: false,
    numPlanes: 3,
    separateUvDeltaQ: false,
    enableCdef: true,
    enableRestoration: true,
    subsamplingX: 1,
    subsamplingY: 1,
    filmGrainParamsPresent: false,
    enableOrderHint: true,
    frameIsIntra: true,
    showFrame: false,
    allowScreenContentTools: true,
    forceIntegerMv: 1,
    orderHint: 14,
    frameWidth: 36,
    frameHeight: 15,
    baseQIdx: 50,
    codedLossless: false,
    loopFilterLevel0: 0,
    cdefBits: 0,
    usesLr: false,
    txMode: 1,
    reducedTxSet: true,
  ),
  (
    seqForceScreenContentTools: 2,
    seqForceIntegerMv: 1,
    orderHintBits: 0,
    frameWidthBitsMinus1: 5,
    frameHeightBitsMinus1: 3,
    enableSuperres: true,
    numPlanes: 3,
    separateUvDeltaQ: true,
    enableCdef: true,
    enableRestoration: true,
    subsamplingX: 1,
    subsamplingY: 1,
    filmGrainParamsPresent: false,
    enableOrderHint: false,
    frameIsIntra: true,
    showFrame: false,
    allowScreenContentTools: false,
    forceIntegerMv: 1,
    orderHint: 0,
    frameWidth: 7,
    frameHeight: 2,
    baseQIdx: 250,
    codedLossless: false,
    loopFilterLevel0: 56,
    cdefBits: 3,
    usesLr: true,
    txMode: 2,
    reducedTxSet: true,
  ),
  (
    seqForceScreenContentTools: 2,
    seqForceIntegerMv: 2,
    orderHintBits: 8,
    frameWidthBitsMinus1: 5,
    frameHeightBitsMinus1: 6,
    enableSuperres: false,
    numPlanes: 3,
    separateUvDeltaQ: false,
    enableCdef: true,
    enableRestoration: true,
    subsamplingX: 1,
    subsamplingY: 1,
    filmGrainParamsPresent: true,
    enableOrderHint: true,
    frameIsIntra: true,
    showFrame: true,
    allowScreenContentTools: true,
    forceIntegerMv: 1,
    orderHint: 30,
    frameWidth: 22,
    frameHeight: 37,
    baseQIdx: 40,
    codedLossless: false,
    loopFilterLevel0: 0,
    cdefBits: 0,
    usesLr: false,
    txMode: 1,
    reducedTxSet: false,
  ),
  (
    seqForceScreenContentTools: 1,
    seqForceIntegerMv: 0,
    orderHintBits: 6,
    frameWidthBitsMinus1: 6,
    frameHeightBitsMinus1: 4,
    enableSuperres: false,
    numPlanes: 3,
    separateUvDeltaQ: false,
    enableCdef: true,
    enableRestoration: true,
    subsamplingX: 1,
    subsamplingY: 1,
    filmGrainParamsPresent: true,
    enableOrderHint: true,
    frameIsIntra: true,
    showFrame: true,
    allowScreenContentTools: true,
    forceIntegerMv: 1,
    orderHint: 43,
    frameWidth: 34,
    frameHeight: 21,
    baseQIdx: 246,
    codedLossless: false,
    loopFilterLevel0: 0,
    cdefBits: 0,
    usesLr: false,
    txMode: 1,
    reducedTxSet: true,
  ),
  (
    seqForceScreenContentTools: 2,
    seqForceIntegerMv: 1,
    orderHintBits: 0,
    frameWidthBitsMinus1: 4,
    frameHeightBitsMinus1: 6,
    enableSuperres: false,
    numPlanes: 3,
    separateUvDeltaQ: false,
    enableCdef: false,
    enableRestoration: true,
    subsamplingX: 1,
    subsamplingY: 1,
    filmGrainParamsPresent: false,
    enableOrderHint: false,
    frameIsIntra: true,
    showFrame: false,
    allowScreenContentTools: true,
    forceIntegerMv: 1,
    orderHint: 0,
    frameWidth: 5,
    frameHeight: 28,
    baseQIdx: 86,
    codedLossless: false,
    loopFilterLevel0: 0,
    cdefBits: 0,
    usesLr: false,
    txMode: 1,
    reducedTxSet: true,
  ),
  (
    seqForceScreenContentTools: 1,
    seqForceIntegerMv: 0,
    orderHintBits: 0,
    frameWidthBitsMinus1: 3,
    frameHeightBitsMinus1: 3,
    enableSuperres: true,
    numPlanes: 3,
    separateUvDeltaQ: false,
    enableCdef: false,
    enableRestoration: false,
    subsamplingX: 1,
    subsamplingY: 1,
    filmGrainParamsPresent: true,
    enableOrderHint: false,
    frameIsIntra: true,
    showFrame: false,
    allowScreenContentTools: true,
    forceIntegerMv: 1,
    orderHint: 0,
    frameWidth: 16,
    frameHeight: 16,
    baseQIdx: 0,
    codedLossless: true,
    loopFilterLevel0: 0,
    cdefBits: 0,
    usesLr: false,
    txMode: 0,
    reducedTxSet: true,
  ),
  (
    seqForceScreenContentTools: 1,
    seqForceIntegerMv: 2,
    orderHintBits: 0,
    frameWidthBitsMinus1: 3,
    frameHeightBitsMinus1: 6,
    enableSuperres: true,
    numPlanes: 3,
    separateUvDeltaQ: false,
    enableCdef: false,
    enableRestoration: false,
    subsamplingX: 1,
    subsamplingY: 1,
    filmGrainParamsPresent: false,
    enableOrderHint: false,
    frameIsIntra: true,
    showFrame: false,
    allowScreenContentTools: true,
    forceIntegerMv: 1,
    orderHint: 0,
    frameWidth: 2,
    frameHeight: 57,
    baseQIdx: 252,
    codedLossless: false,
    loopFilterLevel0: 0,
    cdefBits: 0,
    usesLr: false,
    txMode: 1,
    reducedTxSet: false,
  ),
  (
    seqForceScreenContentTools: 2,
    seqForceIntegerMv: 2,
    orderHintBits: 0,
    frameWidthBitsMinus1: 6,
    frameHeightBitsMinus1: 6,
    enableSuperres: true,
    numPlanes: 3,
    separateUvDeltaQ: false,
    enableCdef: false,
    enableRestoration: true,
    subsamplingX: 1,
    subsamplingY: 1,
    filmGrainParamsPresent: false,
    enableOrderHint: false,
    frameIsIntra: true,
    showFrame: false,
    allowScreenContentTools: false,
    forceIntegerMv: 1,
    orderHint: 0,
    frameWidth: 46,
    frameHeight: 18,
    baseQIdx: 55,
    codedLossless: false,
    loopFilterLevel0: 5,
    cdefBits: 0,
    usesLr: true,
    txMode: 1,
    reducedTxSet: false,
  ),
  (
    seqForceScreenContentTools: 1,
    seqForceIntegerMv: 2,
    orderHintBits: 0,
    frameWidthBitsMinus1: 4,
    frameHeightBitsMinus1: 6,
    enableSuperres: true,
    numPlanes: 3,
    separateUvDeltaQ: false,
    enableCdef: false,
    enableRestoration: false,
    subsamplingX: 1,
    subsamplingY: 1,
    filmGrainParamsPresent: false,
    enableOrderHint: false,
    frameIsIntra: true,
    showFrame: true,
    allowScreenContentTools: true,
    forceIntegerMv: 1,
    orderHint: 0,
    frameWidth: 28,
    frameHeight: 61,
    baseQIdx: 232,
    codedLossless: false,
    loopFilterLevel0: 23,
    cdefBits: 0,
    usesLr: false,
    txMode: 1,
    reducedTxSet: false,
  ),
  (
    seqForceScreenContentTools: 1,
    seqForceIntegerMv: 2,
    orderHintBits: 0,
    frameWidthBitsMinus1: 6,
    frameHeightBitsMinus1: 3,
    enableSuperres: true,
    numPlanes: 3,
    separateUvDeltaQ: false,
    enableCdef: true,
    enableRestoration: false,
    subsamplingX: 1,
    subsamplingY: 1,
    filmGrainParamsPresent: true,
    enableOrderHint: false,
    frameIsIntra: true,
    showFrame: true,
    allowScreenContentTools: true,
    forceIntegerMv: 1,
    orderHint: 0,
    frameWidth: 47,
    frameHeight: 6,
    baseQIdx: 95,
    codedLossless: false,
    loopFilterLevel0: 20,
    cdefBits: 1,
    usesLr: false,
    txMode: 2,
    reducedTxSet: true,
  ),
  (
    seqForceScreenContentTools: 2,
    seqForceIntegerMv: 2,
    orderHintBits: 6,
    frameWidthBitsMinus1: 3,
    frameHeightBitsMinus1: 6,
    enableSuperres: true,
    numPlanes: 3,
    separateUvDeltaQ: false,
    enableCdef: false,
    enableRestoration: true,
    subsamplingX: 1,
    subsamplingY: 1,
    filmGrainParamsPresent: true,
    enableOrderHint: true,
    frameIsIntra: true,
    showFrame: true,
    allowScreenContentTools: true,
    forceIntegerMv: 1,
    orderHint: 4,
    frameWidth: 11,
    frameHeight: 21,
    baseQIdx: 53,
    codedLossless: false,
    loopFilterLevel0: 42,
    cdefBits: 0,
    usesLr: true,
    txMode: 1,
    reducedTxSet: false,
  ),
  (
    seqForceScreenContentTools: 2,
    seqForceIntegerMv: 2,
    orderHintBits: 0,
    frameWidthBitsMinus1: 6,
    frameHeightBitsMinus1: 6,
    enableSuperres: false,
    numPlanes: 3,
    separateUvDeltaQ: true,
    enableCdef: true,
    enableRestoration: true,
    subsamplingX: 1,
    subsamplingY: 1,
    filmGrainParamsPresent: true,
    enableOrderHint: false,
    frameIsIntra: true,
    showFrame: false,
    allowScreenContentTools: false,
    forceIntegerMv: 1,
    orderHint: 0,
    frameWidth: 7,
    frameHeight: 37,
    baseQIdx: 129,
    codedLossless: false,
    loopFilterLevel0: 35,
    cdefBits: 0,
    usesLr: true,
    txMode: 1,
    reducedTxSet: true,
  ),
  (
    seqForceScreenContentTools: 2,
    seqForceIntegerMv: 2,
    orderHintBits: 1,
    frameWidthBitsMinus1: 6,
    frameHeightBitsMinus1: 6,
    enableSuperres: false,
    numPlanes: 3,
    separateUvDeltaQ: false,
    enableCdef: false,
    enableRestoration: false,
    subsamplingX: 1,
    subsamplingY: 1,
    filmGrainParamsPresent: false,
    enableOrderHint: true,
    frameIsIntra: true,
    showFrame: false,
    allowScreenContentTools: true,
    forceIntegerMv: 1,
    orderHint: 1,
    frameWidth: 49,
    frameHeight: 52,
    baseQIdx: 133,
    codedLossless: false,
    loopFilterLevel0: 39,
    cdefBits: 0,
    usesLr: false,
    txMode: 2,
    reducedTxSet: true,
  ),
  (
    seqForceScreenContentTools: 0,
    seqForceIntegerMv: 2,
    orderHintBits: 7,
    frameWidthBitsMinus1: 6,
    frameHeightBitsMinus1: 6,
    enableSuperres: true,
    numPlanes: 3,
    separateUvDeltaQ: false,
    enableCdef: true,
    enableRestoration: true,
    subsamplingX: 1,
    subsamplingY: 1,
    filmGrainParamsPresent: false,
    enableOrderHint: true,
    frameIsIntra: true,
    showFrame: true,
    allowScreenContentTools: false,
    forceIntegerMv: 1,
    orderHint: 68,
    frameWidth: 55,
    frameHeight: 14,
    baseQIdx: 212,
    codedLossless: false,
    loopFilterLevel0: 2,
    cdefBits: 3,
    usesLr: true,
    txMode: 2,
    reducedTxSet: false,
  ),
  (
    seqForceScreenContentTools: 2,
    seqForceIntegerMv: 1,
    orderHintBits: 0,
    frameWidthBitsMinus1: 6,
    frameHeightBitsMinus1: 5,
    enableSuperres: false,
    numPlanes: 3,
    separateUvDeltaQ: true,
    enableCdef: false,
    enableRestoration: true,
    subsamplingX: 1,
    subsamplingY: 1,
    filmGrainParamsPresent: true,
    enableOrderHint: false,
    frameIsIntra: true,
    showFrame: false,
    allowScreenContentTools: true,
    forceIntegerMv: 1,
    orderHint: 0,
    frameWidth: 23,
    frameHeight: 29,
    baseQIdx: 15,
    codedLossless: false,
    loopFilterLevel0: 0,
    cdefBits: 0,
    usesLr: false,
    txMode: 1,
    reducedTxSet: true,
  ),
  (
    seqForceScreenContentTools: 1,
    seqForceIntegerMv: 2,
    orderHintBits: 4,
    frameWidthBitsMinus1: 5,
    frameHeightBitsMinus1: 6,
    enableSuperres: false,
    numPlanes: 3,
    separateUvDeltaQ: true,
    enableCdef: true,
    enableRestoration: false,
    subsamplingX: 1,
    subsamplingY: 1,
    filmGrainParamsPresent: false,
    enableOrderHint: true,
    frameIsIntra: true,
    showFrame: true,
    allowScreenContentTools: true,
    forceIntegerMv: 1,
    orderHint: 11,
    frameWidth: 16,
    frameHeight: 27,
    baseQIdx: 98,
    codedLossless: false,
    loopFilterLevel0: 43,
    cdefBits: 2,
    usesLr: false,
    txMode: 2,
    reducedTxSet: false,
  ),
  (
    seqForceScreenContentTools: 2,
    seqForceIntegerMv: 2,
    orderHintBits: 0,
    frameWidthBitsMinus1: 6,
    frameHeightBitsMinus1: 5,
    enableSuperres: true,
    numPlanes: 3,
    separateUvDeltaQ: false,
    enableCdef: true,
    enableRestoration: false,
    subsamplingX: 1,
    subsamplingY: 1,
    filmGrainParamsPresent: false,
    enableOrderHint: false,
    frameIsIntra: true,
    showFrame: true,
    allowScreenContentTools: true,
    forceIntegerMv: 1,
    orderHint: 0,
    frameWidth: 17,
    frameHeight: 14,
    baseQIdx: 2,
    codedLossless: false,
    loopFilterLevel0: 32,
    cdefBits: 0,
    usesLr: false,
    txMode: 1,
    reducedTxSet: false,
  ),
  (
    seqForceScreenContentTools: 0,
    seqForceIntegerMv: 2,
    orderHintBits: 6,
    frameWidthBitsMinus1: 6,
    frameHeightBitsMinus1: 3,
    enableSuperres: true,
    numPlanes: 3,
    separateUvDeltaQ: false,
    enableCdef: true,
    enableRestoration: true,
    subsamplingX: 1,
    subsamplingY: 1,
    filmGrainParamsPresent: true,
    enableOrderHint: true,
    frameIsIntra: true,
    showFrame: true,
    allowScreenContentTools: false,
    forceIntegerMv: 1,
    orderHint: 55,
    frameWidth: 36,
    frameHeight: 15,
    baseQIdx: 109,
    codedLossless: false,
    loopFilterLevel0: 35,
    cdefBits: 1,
    usesLr: false,
    txMode: 1,
    reducedTxSet: true,
  ),
  (
    seqForceScreenContentTools: 2,
    seqForceIntegerMv: 2,
    orderHintBits: 8,
    frameWidthBitsMinus1: 3,
    frameHeightBitsMinus1: 4,
    enableSuperres: true,
    numPlanes: 3,
    separateUvDeltaQ: false,
    enableCdef: true,
    enableRestoration: true,
    subsamplingX: 1,
    subsamplingY: 1,
    filmGrainParamsPresent: true,
    enableOrderHint: true,
    frameIsIntra: true,
    showFrame: false,
    allowScreenContentTools: true,
    forceIntegerMv: 1,
    orderHint: 216,
    frameWidth: 13,
    frameHeight: 30,
    baseQIdx: 0,
    codedLossless: true,
    loopFilterLevel0: 0,
    cdefBits: 0,
    usesLr: false,
    txMode: 0,
    reducedTxSet: false,
  ),
  (
    seqForceScreenContentTools: 2,
    seqForceIntegerMv: 2,
    orderHintBits: 5,
    frameWidthBitsMinus1: 6,
    frameHeightBitsMinus1: 3,
    enableSuperres: true,
    numPlanes: 3,
    separateUvDeltaQ: true,
    enableCdef: false,
    enableRestoration: true,
    subsamplingX: 1,
    subsamplingY: 1,
    filmGrainParamsPresent: true,
    enableOrderHint: true,
    frameIsIntra: true,
    showFrame: true,
    allowScreenContentTools: true,
    forceIntegerMv: 1,
    orderHint: 18,
    frameWidth: 24,
    frameHeight: 15,
    baseQIdx: 22,
    codedLossless: false,
    loopFilterLevel0: 5,
    cdefBits: 0,
    usesLr: true,
    txMode: 1,
    reducedTxSet: true,
  ),
  (
    seqForceScreenContentTools: 1,
    seqForceIntegerMv: 1,
    orderHintBits: 0,
    frameWidthBitsMinus1: 6,
    frameHeightBitsMinus1: 5,
    enableSuperres: true,
    numPlanes: 3,
    separateUvDeltaQ: true,
    enableCdef: true,
    enableRestoration: false,
    subsamplingX: 1,
    subsamplingY: 1,
    filmGrainParamsPresent: true,
    enableOrderHint: false,
    frameIsIntra: true,
    showFrame: true,
    allowScreenContentTools: true,
    forceIntegerMv: 1,
    orderHint: 0,
    frameWidth: 12,
    frameHeight: 44,
    baseQIdx: 30,
    codedLossless: false,
    loopFilterLevel0: 0,
    cdefBits: 0,
    usesLr: false,
    txMode: 2,
    reducedTxSet: false,
  ),
  (
    seqForceScreenContentTools: 2,
    seqForceIntegerMv: 1,
    orderHintBits: 7,
    frameWidthBitsMinus1: 3,
    frameHeightBitsMinus1: 5,
    enableSuperres: true,
    numPlanes: 3,
    separateUvDeltaQ: false,
    enableCdef: true,
    enableRestoration: true,
    subsamplingX: 1,
    subsamplingY: 1,
    filmGrainParamsPresent: false,
    enableOrderHint: true,
    frameIsIntra: true,
    showFrame: false,
    allowScreenContentTools: true,
    forceIntegerMv: 1,
    orderHint: 111,
    frameWidth: 14,
    frameHeight: 28,
    baseQIdx: 244,
    codedLossless: false,
    loopFilterLevel0: 62,
    cdefBits: 1,
    usesLr: true,
    txMode: 1,
    reducedTxSet: true,
  ),
  (
    seqForceScreenContentTools: 2,
    seqForceIntegerMv: 2,
    orderHintBits: 0,
    frameWidthBitsMinus1: 6,
    frameHeightBitsMinus1: 5,
    enableSuperres: true,
    numPlanes: 3,
    separateUvDeltaQ: false,
    enableCdef: false,
    enableRestoration: false,
    subsamplingX: 1,
    subsamplingY: 1,
    filmGrainParamsPresent: true,
    enableOrderHint: false,
    frameIsIntra: true,
    showFrame: false,
    allowScreenContentTools: false,
    forceIntegerMv: 1,
    orderHint: 0,
    frameWidth: 12,
    frameHeight: 37,
    baseQIdx: 0,
    codedLossless: true,
    loopFilterLevel0: 0,
    cdefBits: 0,
    usesLr: false,
    txMode: 0,
    reducedTxSet: true,
  ),
  (
    seqForceScreenContentTools: 2,
    seqForceIntegerMv: 0,
    orderHintBits: 0,
    frameWidthBitsMinus1: 3,
    frameHeightBitsMinus1: 6,
    enableSuperres: false,
    numPlanes: 3,
    separateUvDeltaQ: true,
    enableCdef: false,
    enableRestoration: true,
    subsamplingX: 1,
    subsamplingY: 1,
    filmGrainParamsPresent: true,
    enableOrderHint: false,
    frameIsIntra: true,
    showFrame: true,
    allowScreenContentTools: false,
    forceIntegerMv: 1,
    orderHint: 0,
    frameWidth: 12,
    frameHeight: 5,
    baseQIdx: 114,
    codedLossless: false,
    loopFilterLevel0: 2,
    cdefBits: 0,
    usesLr: false,
    txMode: 1,
    reducedTxSet: false,
  ),
  (
    seqForceScreenContentTools: 2,
    seqForceIntegerMv: 2,
    orderHintBits: 0,
    frameWidthBitsMinus1: 3,
    frameHeightBitsMinus1: 5,
    enableSuperres: true,
    numPlanes: 3,
    separateUvDeltaQ: true,
    enableCdef: true,
    enableRestoration: true,
    subsamplingX: 1,
    subsamplingY: 1,
    filmGrainParamsPresent: false,
    enableOrderHint: false,
    frameIsIntra: true,
    showFrame: false,
    allowScreenContentTools: false,
    forceIntegerMv: 1,
    orderHint: 0,
    frameWidth: 14,
    frameHeight: 25,
    baseQIdx: 235,
    codedLossless: false,
    loopFilterLevel0: 12,
    cdefBits: 0,
    usesLr: true,
    txMode: 2,
    reducedTxSet: true,
  ),
  (
    seqForceScreenContentTools: 2,
    seqForceIntegerMv: 2,
    orderHintBits: 0,
    frameWidthBitsMinus1: 5,
    frameHeightBitsMinus1: 6,
    enableSuperres: false,
    numPlanes: 3,
    separateUvDeltaQ: false,
    enableCdef: false,
    enableRestoration: true,
    subsamplingX: 1,
    subsamplingY: 1,
    filmGrainParamsPresent: true,
    enableOrderHint: false,
    frameIsIntra: true,
    showFrame: false,
    allowScreenContentTools: false,
    forceIntegerMv: 1,
    orderHint: 0,
    frameWidth: 61,
    frameHeight: 7,
    baseQIdx: 188,
    codedLossless: false,
    loopFilterLevel0: 18,
    cdefBits: 0,
    usesLr: true,
    txMode: 2,
    reducedTxSet: true,
  ),
  (
    seqForceScreenContentTools: 2,
    seqForceIntegerMv: 2,
    orderHintBits: 0,
    frameWidthBitsMinus1: 5,
    frameHeightBitsMinus1: 5,
    enableSuperres: false,
    numPlanes: 3,
    separateUvDeltaQ: true,
    enableCdef: false,
    enableRestoration: false,
    subsamplingX: 1,
    subsamplingY: 1,
    filmGrainParamsPresent: false,
    enableOrderHint: false,
    frameIsIntra: true,
    showFrame: false,
    allowScreenContentTools: true,
    forceIntegerMv: 1,
    orderHint: 0,
    frameWidth: 42,
    frameHeight: 50,
    baseQIdx: 0,
    codedLossless: true,
    loopFilterLevel0: 0,
    cdefBits: 0,
    usesLr: false,
    txMode: 0,
    reducedTxSet: true,
  ),
  (
    seqForceScreenContentTools: 1,
    seqForceIntegerMv: 2,
    orderHintBits: 3,
    frameWidthBitsMinus1: 6,
    frameHeightBitsMinus1: 5,
    enableSuperres: false,
    numPlanes: 3,
    separateUvDeltaQ: true,
    enableCdef: true,
    enableRestoration: true,
    subsamplingX: 1,
    subsamplingY: 1,
    filmGrainParamsPresent: false,
    enableOrderHint: true,
    frameIsIntra: true,
    showFrame: false,
    allowScreenContentTools: true,
    forceIntegerMv: 1,
    orderHint: 5,
    frameWidth: 3,
    frameHeight: 6,
    baseQIdx: 114,
    codedLossless: false,
    loopFilterLevel0: 0,
    cdefBits: 0,
    usesLr: false,
    txMode: 2,
    reducedTxSet: true,
  ),
  (
    seqForceScreenContentTools: 2,
    seqForceIntegerMv: 2,
    orderHintBits: 0,
    frameWidthBitsMinus1: 5,
    frameHeightBitsMinus1: 5,
    enableSuperres: false,
    numPlanes: 3,
    separateUvDeltaQ: true,
    enableCdef: true,
    enableRestoration: true,
    subsamplingX: 1,
    subsamplingY: 1,
    filmGrainParamsPresent: true,
    enableOrderHint: false,
    frameIsIntra: true,
    showFrame: true,
    allowScreenContentTools: true,
    forceIntegerMv: 1,
    orderHint: 0,
    frameWidth: 41,
    frameHeight: 16,
    baseQIdx: 216,
    codedLossless: false,
    loopFilterLevel0: 0,
    cdefBits: 0,
    usesLr: false,
    txMode: 2,
    reducedTxSet: true,
  ),
  (
    seqForceScreenContentTools: 2,
    seqForceIntegerMv: 0,
    orderHintBits: 7,
    frameWidthBitsMinus1: 5,
    frameHeightBitsMinus1: 3,
    enableSuperres: false,
    numPlanes: 3,
    separateUvDeltaQ: true,
    enableCdef: true,
    enableRestoration: true,
    subsamplingX: 1,
    subsamplingY: 1,
    filmGrainParamsPresent: true,
    enableOrderHint: true,
    frameIsIntra: true,
    showFrame: false,
    allowScreenContentTools: true,
    forceIntegerMv: 1,
    orderHint: 55,
    frameWidth: 47,
    frameHeight: 16,
    baseQIdx: 249,
    codedLossless: false,
    loopFilterLevel0: 0,
    cdefBits: 0,
    usesLr: false,
    txMode: 1,
    reducedTxSet: false,
  ),
  (
    seqForceScreenContentTools: 2,
    seqForceIntegerMv: 2,
    orderHintBits: 5,
    frameWidthBitsMinus1: 4,
    frameHeightBitsMinus1: 4,
    enableSuperres: true,
    numPlanes: 3,
    separateUvDeltaQ: false,
    enableCdef: true,
    enableRestoration: true,
    subsamplingX: 1,
    subsamplingY: 1,
    filmGrainParamsPresent: true,
    enableOrderHint: true,
    frameIsIntra: true,
    showFrame: true,
    allowScreenContentTools: true,
    forceIntegerMv: 1,
    orderHint: 1,
    frameWidth: 27,
    frameHeight: 20,
    baseQIdx: 34,
    codedLossless: false,
    loopFilterLevel0: 0,
    cdefBits: 0,
    usesLr: false,
    txMode: 1,
    reducedTxSet: true,
  ),
  (
    seqForceScreenContentTools: 2,
    seqForceIntegerMv: 1,
    orderHintBits: 0,
    frameWidthBitsMinus1: 5,
    frameHeightBitsMinus1: 6,
    enableSuperres: false,
    numPlanes: 3,
    separateUvDeltaQ: false,
    enableCdef: false,
    enableRestoration: false,
    subsamplingX: 1,
    subsamplingY: 1,
    filmGrainParamsPresent: true,
    enableOrderHint: false,
    frameIsIntra: true,
    showFrame: true,
    allowScreenContentTools: false,
    forceIntegerMv: 1,
    orderHint: 0,
    frameWidth: 35,
    frameHeight: 17,
    baseQIdx: 233,
    codedLossless: false,
    loopFilterLevel0: 34,
    cdefBits: 0,
    usesLr: false,
    txMode: 1,
    reducedTxSet: true,
  ),
  (
    seqForceScreenContentTools: 1,
    seqForceIntegerMv: 2,
    orderHintBits: 0,
    frameWidthBitsMinus1: 3,
    frameHeightBitsMinus1: 4,
    enableSuperres: true,
    numPlanes: 3,
    separateUvDeltaQ: true,
    enableCdef: true,
    enableRestoration: false,
    subsamplingX: 1,
    subsamplingY: 1,
    filmGrainParamsPresent: false,
    enableOrderHint: false,
    frameIsIntra: true,
    showFrame: true,
    allowScreenContentTools: true,
    forceIntegerMv: 1,
    orderHint: 0,
    frameWidth: 3,
    frameHeight: 4,
    baseQIdx: 92,
    codedLossless: false,
    loopFilterLevel0: 0,
    cdefBits: 0,
    usesLr: false,
    txMode: 2,
    reducedTxSet: false,
  ),
  (
    seqForceScreenContentTools: 0,
    seqForceIntegerMv: 2,
    orderHintBits: 5,
    frameWidthBitsMinus1: 5,
    frameHeightBitsMinus1: 5,
    enableSuperres: false,
    numPlanes: 3,
    separateUvDeltaQ: true,
    enableCdef: false,
    enableRestoration: false,
    subsamplingX: 1,
    subsamplingY: 1,
    filmGrainParamsPresent: true,
    enableOrderHint: true,
    frameIsIntra: true,
    showFrame: false,
    allowScreenContentTools: false,
    forceIntegerMv: 1,
    orderHint: 6,
    frameWidth: 41,
    frameHeight: 59,
    baseQIdx: 0,
    codedLossless: true,
    loopFilterLevel0: 0,
    cdefBits: 0,
    usesLr: false,
    txMode: 0,
    reducedTxSet: true,
  ),
  (
    seqForceScreenContentTools: 2,
    seqForceIntegerMv: 2,
    orderHintBits: 6,
    frameWidthBitsMinus1: 6,
    frameHeightBitsMinus1: 5,
    enableSuperres: true,
    numPlanes: 3,
    separateUvDeltaQ: false,
    enableCdef: false,
    enableRestoration: false,
    subsamplingX: 1,
    subsamplingY: 1,
    filmGrainParamsPresent: false,
    enableOrderHint: true,
    frameIsIntra: true,
    showFrame: true,
    allowScreenContentTools: true,
    forceIntegerMv: 1,
    orderHint: 20,
    frameWidth: 48,
    frameHeight: 37,
    baseQIdx: 88,
    codedLossless: false,
    loopFilterLevel0: 14,
    cdefBits: 0,
    usesLr: false,
    txMode: 2,
    reducedTxSet: false,
  ),
  (
    seqForceScreenContentTools: 1,
    seqForceIntegerMv: 2,
    orderHintBits: 6,
    frameWidthBitsMinus1: 5,
    frameHeightBitsMinus1: 5,
    enableSuperres: true,
    numPlanes: 3,
    separateUvDeltaQ: true,
    enableCdef: true,
    enableRestoration: false,
    subsamplingX: 1,
    subsamplingY: 1,
    filmGrainParamsPresent: true,
    enableOrderHint: true,
    frameIsIntra: true,
    showFrame: false,
    allowScreenContentTools: true,
    forceIntegerMv: 1,
    orderHint: 12,
    frameWidth: 50,
    frameHeight: 35,
    baseQIdx: 174,
    codedLossless: false,
    loopFilterLevel0: 0,
    cdefBits: 0,
    usesLr: false,
    txMode: 1,
    reducedTxSet: true,
  ),
  (
    seqForceScreenContentTools: 2,
    seqForceIntegerMv: 1,
    orderHintBits: 4,
    frameWidthBitsMinus1: 3,
    frameHeightBitsMinus1: 5,
    enableSuperres: false,
    numPlanes: 3,
    separateUvDeltaQ: false,
    enableCdef: false,
    enableRestoration: true,
    subsamplingX: 1,
    subsamplingY: 1,
    filmGrainParamsPresent: false,
    enableOrderHint: true,
    frameIsIntra: true,
    showFrame: false,
    allowScreenContentTools: false,
    forceIntegerMv: 1,
    orderHint: 2,
    frameWidth: 12,
    frameHeight: 24,
    baseQIdx: 135,
    codedLossless: false,
    loopFilterLevel0: 63,
    cdefBits: 0,
    usesLr: true,
    txMode: 1,
    reducedTxSet: true,
  ),
  (
    seqForceScreenContentTools: 2,
    seqForceIntegerMv: 1,
    orderHintBits: 1,
    frameWidthBitsMinus1: 4,
    frameHeightBitsMinus1: 3,
    enableSuperres: true,
    numPlanes: 3,
    separateUvDeltaQ: false,
    enableCdef: true,
    enableRestoration: false,
    subsamplingX: 1,
    subsamplingY: 1,
    filmGrainParamsPresent: true,
    enableOrderHint: true,
    frameIsIntra: true,
    showFrame: false,
    allowScreenContentTools: false,
    forceIntegerMv: 1,
    orderHint: 0,
    frameWidth: 9,
    frameHeight: 15,
    baseQIdx: 0,
    codedLossless: true,
    loopFilterLevel0: 0,
    cdefBits: 0,
    usesLr: false,
    txMode: 0,
    reducedTxSet: true,
  ),
  (
    seqForceScreenContentTools: 1,
    seqForceIntegerMv: 0,
    orderHintBits: 1,
    frameWidthBitsMinus1: 6,
    frameHeightBitsMinus1: 6,
    enableSuperres: false,
    numPlanes: 3,
    separateUvDeltaQ: true,
    enableCdef: false,
    enableRestoration: false,
    subsamplingX: 1,
    subsamplingY: 1,
    filmGrainParamsPresent: true,
    enableOrderHint: true,
    frameIsIntra: true,
    showFrame: false,
    allowScreenContentTools: true,
    forceIntegerMv: 1,
    orderHint: 1,
    frameWidth: 50,
    frameHeight: 51,
    baseQIdx: 119,
    codedLossless: false,
    loopFilterLevel0: 0,
    cdefBits: 0,
    usesLr: false,
    txMode: 2,
    reducedTxSet: false,
  ),
  (
    seqForceScreenContentTools: 0,
    seqForceIntegerMv: 2,
    orderHintBits: 4,
    frameWidthBitsMinus1: 3,
    frameHeightBitsMinus1: 3,
    enableSuperres: false,
    numPlanes: 3,
    separateUvDeltaQ: false,
    enableCdef: true,
    enableRestoration: false,
    subsamplingX: 1,
    subsamplingY: 1,
    filmGrainParamsPresent: false,
    enableOrderHint: true,
    frameIsIntra: true,
    showFrame: true,
    allowScreenContentTools: false,
    forceIntegerMv: 1,
    orderHint: 14,
    frameWidth: 6,
    frameHeight: 7,
    baseQIdx: 44,
    codedLossless: false,
    loopFilterLevel0: 1,
    cdefBits: 1,
    usesLr: false,
    txMode: 2,
    reducedTxSet: false,
  ),
  (
    seqForceScreenContentTools: 2,
    seqForceIntegerMv: 0,
    orderHintBits: 0,
    frameWidthBitsMinus1: 5,
    frameHeightBitsMinus1: 3,
    enableSuperres: false,
    numPlanes: 3,
    separateUvDeltaQ: false,
    enableCdef: true,
    enableRestoration: false,
    subsamplingX: 1,
    subsamplingY: 1,
    filmGrainParamsPresent: true,
    enableOrderHint: false,
    frameIsIntra: true,
    showFrame: false,
    allowScreenContentTools: true,
    forceIntegerMv: 1,
    orderHint: 0,
    frameWidth: 20,
    frameHeight: 3,
    baseQIdx: 251,
    codedLossless: false,
    loopFilterLevel0: 0,
    cdefBits: 0,
    usesLr: false,
    txMode: 1,
    reducedTxSet: false,
  ),
  (
    seqForceScreenContentTools: 1,
    seqForceIntegerMv: 2,
    orderHintBits: 0,
    frameWidthBitsMinus1: 3,
    frameHeightBitsMinus1: 3,
    enableSuperres: true,
    numPlanes: 3,
    separateUvDeltaQ: false,
    enableCdef: false,
    enableRestoration: true,
    subsamplingX: 1,
    subsamplingY: 1,
    filmGrainParamsPresent: false,
    enableOrderHint: false,
    frameIsIntra: true,
    showFrame: true,
    allowScreenContentTools: true,
    forceIntegerMv: 1,
    orderHint: 0,
    frameWidth: 3,
    frameHeight: 5,
    baseQIdx: 182,
    codedLossless: false,
    loopFilterLevel0: 37,
    cdefBits: 0,
    usesLr: true,
    txMode: 1,
    reducedTxSet: false,
  ),
  (
    seqForceScreenContentTools: 0,
    seqForceIntegerMv: 2,
    orderHintBits: 0,
    frameWidthBitsMinus1: 4,
    frameHeightBitsMinus1: 4,
    enableSuperres: false,
    numPlanes: 3,
    separateUvDeltaQ: true,
    enableCdef: true,
    enableRestoration: true,
    subsamplingX: 1,
    subsamplingY: 1,
    filmGrainParamsPresent: true,
    enableOrderHint: false,
    frameIsIntra: true,
    showFrame: false,
    allowScreenContentTools: false,
    forceIntegerMv: 1,
    orderHint: 0,
    frameWidth: 32,
    frameHeight: 28,
    baseQIdx: 207,
    codedLossless: false,
    loopFilterLevel0: 15,
    cdefBits: 3,
    usesLr: true,
    txMode: 2,
    reducedTxSet: true,
  ),
  (
    seqForceScreenContentTools: 2,
    seqForceIntegerMv: 1,
    orderHintBits: 3,
    frameWidthBitsMinus1: 4,
    frameHeightBitsMinus1: 4,
    enableSuperres: true,
    numPlanes: 3,
    separateUvDeltaQ: false,
    enableCdef: true,
    enableRestoration: true,
    subsamplingX: 1,
    subsamplingY: 1,
    filmGrainParamsPresent: false,
    enableOrderHint: true,
    frameIsIntra: true,
    showFrame: false,
    allowScreenContentTools: true,
    forceIntegerMv: 1,
    orderHint: 2,
    frameWidth: 7,
    frameHeight: 5,
    baseQIdx: 170,
    codedLossless: false,
    loopFilterLevel0: 25,
    cdefBits: 2,
    usesLr: true,
    txMode: 1,
    reducedTxSet: true,
  ),
  (
    seqForceScreenContentTools: 2,
    seqForceIntegerMv: 2,
    orderHintBits: 8,
    frameWidthBitsMinus1: 5,
    frameHeightBitsMinus1: 3,
    enableSuperres: true,
    numPlanes: 3,
    separateUvDeltaQ: false,
    enableCdef: true,
    enableRestoration: false,
    subsamplingX: 1,
    subsamplingY: 1,
    filmGrainParamsPresent: false,
    enableOrderHint: true,
    frameIsIntra: true,
    showFrame: false,
    allowScreenContentTools: false,
    forceIntegerMv: 1,
    orderHint: 40,
    frameWidth: 35,
    frameHeight: 16,
    baseQIdx: 0,
    codedLossless: true,
    loopFilterLevel0: 0,
    cdefBits: 0,
    usesLr: false,
    txMode: 0,
    reducedTxSet: false,
  ),
  (
    seqForceScreenContentTools: 1,
    seqForceIntegerMv: 0,
    orderHintBits: 7,
    frameWidthBitsMinus1: 5,
    frameHeightBitsMinus1: 6,
    enableSuperres: false,
    numPlanes: 3,
    separateUvDeltaQ: false,
    enableCdef: true,
    enableRestoration: true,
    subsamplingX: 1,
    subsamplingY: 1,
    filmGrainParamsPresent: true,
    enableOrderHint: true,
    frameIsIntra: true,
    showFrame: false,
    allowScreenContentTools: true,
    forceIntegerMv: 1,
    orderHint: 45,
    frameWidth: 25,
    frameHeight: 51,
    baseQIdx: 141,
    codedLossless: false,
    loopFilterLevel0: 0,
    cdefBits: 0,
    usesLr: false,
    txMode: 2,
    reducedTxSet: false,
  ),
  (
    seqForceScreenContentTools: 1,
    seqForceIntegerMv: 2,
    orderHintBits: 8,
    frameWidthBitsMinus1: 5,
    frameHeightBitsMinus1: 4,
    enableSuperres: true,
    numPlanes: 3,
    separateUvDeltaQ: false,
    enableCdef: true,
    enableRestoration: false,
    subsamplingX: 1,
    subsamplingY: 1,
    filmGrainParamsPresent: true,
    enableOrderHint: true,
    frameIsIntra: true,
    showFrame: true,
    allowScreenContentTools: true,
    forceIntegerMv: 1,
    orderHint: 137,
    frameWidth: 26,
    frameHeight: 12,
    baseQIdx: 173,
    codedLossless: false,
    loopFilterLevel0: 0,
    cdefBits: 0,
    usesLr: false,
    txMode: 1,
    reducedTxSet: true,
  ),
  (
    seqForceScreenContentTools: 2,
    seqForceIntegerMv: 2,
    orderHintBits: 0,
    frameWidthBitsMinus1: 6,
    frameHeightBitsMinus1: 5,
    enableSuperres: false,
    numPlanes: 3,
    separateUvDeltaQ: true,
    enableCdef: true,
    enableRestoration: false,
    subsamplingX: 1,
    subsamplingY: 1,
    filmGrainParamsPresent: true,
    enableOrderHint: false,
    frameIsIntra: true,
    showFrame: true,
    allowScreenContentTools: true,
    forceIntegerMv: 1,
    orderHint: 0,
    frameWidth: 31,
    frameHeight: 14,
    baseQIdx: 0,
    codedLossless: true,
    loopFilterLevel0: 0,
    cdefBits: 0,
    usesLr: false,
    txMode: 0,
    reducedTxSet: true,
  ),
  (
    seqForceScreenContentTools: 1,
    seqForceIntegerMv: 0,
    orderHintBits: 0,
    frameWidthBitsMinus1: 6,
    frameHeightBitsMinus1: 5,
    enableSuperres: false,
    numPlanes: 3,
    separateUvDeltaQ: false,
    enableCdef: true,
    enableRestoration: false,
    subsamplingX: 1,
    subsamplingY: 1,
    filmGrainParamsPresent: true,
    enableOrderHint: false,
    frameIsIntra: true,
    showFrame: false,
    allowScreenContentTools: true,
    forceIntegerMv: 1,
    orderHint: 0,
    frameWidth: 64,
    frameHeight: 12,
    baseQIdx: 254,
    codedLossless: false,
    loopFilterLevel0: 42,
    cdefBits: 1,
    usesLr: false,
    txMode: 1,
    reducedTxSet: true,
  ),
  (
    seqForceScreenContentTools: 2,
    seqForceIntegerMv: 0,
    orderHintBits: 8,
    frameWidthBitsMinus1: 4,
    frameHeightBitsMinus1: 4,
    enableSuperres: true,
    numPlanes: 3,
    separateUvDeltaQ: true,
    enableCdef: true,
    enableRestoration: true,
    subsamplingX: 1,
    subsamplingY: 1,
    filmGrainParamsPresent: false,
    enableOrderHint: true,
    frameIsIntra: true,
    showFrame: true,
    allowScreenContentTools: true,
    forceIntegerMv: 1,
    orderHint: 73,
    frameWidth: 22,
    frameHeight: 2,
    baseQIdx: 92,
    codedLossless: false,
    loopFilterLevel0: 0,
    cdefBits: 0,
    usesLr: false,
    txMode: 2,
    reducedTxSet: true,
  ),
  (
    seqForceScreenContentTools: 2,
    seqForceIntegerMv: 2,
    orderHintBits: 0,
    frameWidthBitsMinus1: 3,
    frameHeightBitsMinus1: 5,
    enableSuperres: false,
    numPlanes: 3,
    separateUvDeltaQ: true,
    enableCdef: true,
    enableRestoration: true,
    subsamplingX: 1,
    subsamplingY: 1,
    filmGrainParamsPresent: false,
    enableOrderHint: false,
    frameIsIntra: true,
    showFrame: false,
    allowScreenContentTools: true,
    forceIntegerMv: 1,
    orderHint: 0,
    frameWidth: 8,
    frameHeight: 34,
    baseQIdx: 118,
    codedLossless: false,
    loopFilterLevel0: 0,
    cdefBits: 0,
    usesLr: false,
    txMode: 2,
    reducedTxSet: true,
  ),
  (
    seqForceScreenContentTools: 2,
    seqForceIntegerMv: 2,
    orderHintBits: 3,
    frameWidthBitsMinus1: 5,
    frameHeightBitsMinus1: 4,
    enableSuperres: false,
    numPlanes: 3,
    separateUvDeltaQ: true,
    enableCdef: false,
    enableRestoration: false,
    subsamplingX: 1,
    subsamplingY: 1,
    filmGrainParamsPresent: false,
    enableOrderHint: true,
    frameIsIntra: true,
    showFrame: true,
    allowScreenContentTools: false,
    forceIntegerMv: 1,
    orderHint: 3,
    frameWidth: 18,
    frameHeight: 30,
    baseQIdx: 131,
    codedLossless: false,
    loopFilterLevel0: 29,
    cdefBits: 0,
    usesLr: false,
    txMode: 1,
    reducedTxSet: false,
  ),
  (
    seqForceScreenContentTools: 1,
    seqForceIntegerMv: 2,
    orderHintBits: 2,
    frameWidthBitsMinus1: 4,
    frameHeightBitsMinus1: 3,
    enableSuperres: false,
    numPlanes: 3,
    separateUvDeltaQ: true,
    enableCdef: false,
    enableRestoration: true,
    subsamplingX: 1,
    subsamplingY: 1,
    filmGrainParamsPresent: true,
    enableOrderHint: true,
    frameIsIntra: true,
    showFrame: true,
    allowScreenContentTools: true,
    forceIntegerMv: 1,
    orderHint: 1,
    frameWidth: 32,
    frameHeight: 3,
    baseQIdx: 190,
    codedLossless: false,
    loopFilterLevel0: 0,
    cdefBits: 0,
    usesLr: false,
    txMode: 2,
    reducedTxSet: true,
  ),
  (
    seqForceScreenContentTools: 2,
    seqForceIntegerMv: 1,
    orderHintBits: 1,
    frameWidthBitsMinus1: 6,
    frameHeightBitsMinus1: 3,
    enableSuperres: true,
    numPlanes: 3,
    separateUvDeltaQ: false,
    enableCdef: false,
    enableRestoration: true,
    subsamplingX: 1,
    subsamplingY: 1,
    filmGrainParamsPresent: false,
    enableOrderHint: true,
    frameIsIntra: true,
    showFrame: true,
    allowScreenContentTools: false,
    forceIntegerMv: 1,
    orderHint: 0,
    frameWidth: 54,
    frameHeight: 15,
    baseQIdx: 149,
    codedLossless: false,
    loopFilterLevel0: 37,
    cdefBits: 0,
    usesLr: true,
    txMode: 2,
    reducedTxSet: true,
  ),
  (
    seqForceScreenContentTools: 1,
    seqForceIntegerMv: 0,
    orderHintBits: 0,
    frameWidthBitsMinus1: 5,
    frameHeightBitsMinus1: 3,
    enableSuperres: false,
    numPlanes: 3,
    separateUvDeltaQ: false,
    enableCdef: true,
    enableRestoration: true,
    subsamplingX: 1,
    subsamplingY: 1,
    filmGrainParamsPresent: false,
    enableOrderHint: false,
    frameIsIntra: true,
    showFrame: true,
    allowScreenContentTools: true,
    forceIntegerMv: 1,
    orderHint: 0,
    frameWidth: 17,
    frameHeight: 10,
    baseQIdx: 164,
    codedLossless: false,
    loopFilterLevel0: 14,
    cdefBits: 0,
    usesLr: true,
    txMode: 2,
    reducedTxSet: true,
  ),
  (
    seqForceScreenContentTools: 2,
    seqForceIntegerMv: 2,
    orderHintBits: 6,
    frameWidthBitsMinus1: 4,
    frameHeightBitsMinus1: 5,
    enableSuperres: true,
    numPlanes: 3,
    separateUvDeltaQ: true,
    enableCdef: false,
    enableRestoration: true,
    subsamplingX: 1,
    subsamplingY: 1,
    filmGrainParamsPresent: false,
    enableOrderHint: true,
    frameIsIntra: true,
    showFrame: true,
    allowScreenContentTools: true,
    forceIntegerMv: 1,
    orderHint: 57,
    frameWidth: 28,
    frameHeight: 16,
    baseQIdx: 148,
    codedLossless: false,
    loopFilterLevel0: 6,
    cdefBits: 0,
    usesLr: true,
    txMode: 2,
    reducedTxSet: false,
  ),
  (
    seqForceScreenContentTools: 1,
    seqForceIntegerMv: 0,
    orderHintBits: 1,
    frameWidthBitsMinus1: 4,
    frameHeightBitsMinus1: 3,
    enableSuperres: false,
    numPlanes: 3,
    separateUvDeltaQ: true,
    enableCdef: true,
    enableRestoration: true,
    subsamplingX: 1,
    subsamplingY: 1,
    filmGrainParamsPresent: false,
    enableOrderHint: true,
    frameIsIntra: true,
    showFrame: false,
    allowScreenContentTools: true,
    forceIntegerMv: 1,
    orderHint: 1,
    frameWidth: 20,
    frameHeight: 4,
    baseQIdx: 181,
    codedLossless: false,
    loopFilterLevel0: 0,
    cdefBits: 0,
    usesLr: false,
    txMode: 1,
    reducedTxSet: true,
  ),
  (
    seqForceScreenContentTools: 2,
    seqForceIntegerMv: 1,
    orderHintBits: 2,
    frameWidthBitsMinus1: 3,
    frameHeightBitsMinus1: 5,
    enableSuperres: true,
    numPlanes: 3,
    separateUvDeltaQ: true,
    enableCdef: false,
    enableRestoration: false,
    subsamplingX: 1,
    subsamplingY: 1,
    filmGrainParamsPresent: true,
    enableOrderHint: true,
    frameIsIntra: true,
    showFrame: true,
    allowScreenContentTools: false,
    forceIntegerMv: 1,
    orderHint: 2,
    frameWidth: 1,
    frameHeight: 52,
    baseQIdx: 129,
    codedLossless: false,
    loopFilterLevel0: 2,
    cdefBits: 0,
    usesLr: false,
    txMode: 2,
    reducedTxSet: true,
  ),
  (
    seqForceScreenContentTools: 2,
    seqForceIntegerMv: 1,
    orderHintBits: 1,
    frameWidthBitsMinus1: 5,
    frameHeightBitsMinus1: 6,
    enableSuperres: true,
    numPlanes: 3,
    separateUvDeltaQ: false,
    enableCdef: true,
    enableRestoration: false,
    subsamplingX: 1,
    subsamplingY: 1,
    filmGrainParamsPresent: true,
    enableOrderHint: true,
    frameIsIntra: true,
    showFrame: true,
    allowScreenContentTools: true,
    forceIntegerMv: 1,
    orderHint: 0,
    frameWidth: 29,
    frameHeight: 54,
    baseQIdx: 21,
    codedLossless: false,
    loopFilterLevel0: 30,
    cdefBits: 0,
    usesLr: false,
    txMode: 2,
    reducedTxSet: true,
  ),
  (
    seqForceScreenContentTools: 2,
    seqForceIntegerMv: 0,
    orderHintBits: 0,
    frameWidthBitsMinus1: 6,
    frameHeightBitsMinus1: 5,
    enableSuperres: false,
    numPlanes: 3,
    separateUvDeltaQ: true,
    enableCdef: true,
    enableRestoration: false,
    subsamplingX: 1,
    subsamplingY: 1,
    filmGrainParamsPresent: true,
    enableOrderHint: false,
    frameIsIntra: true,
    showFrame: true,
    allowScreenContentTools: true,
    forceIntegerMv: 1,
    orderHint: 0,
    frameWidth: 14,
    frameHeight: 63,
    baseQIdx: 0,
    codedLossless: true,
    loopFilterLevel0: 0,
    cdefBits: 0,
    usesLr: false,
    txMode: 0,
    reducedTxSet: false,
  ),
  (
    seqForceScreenContentTools: 2,
    seqForceIntegerMv: 2,
    orderHintBits: 0,
    frameWidthBitsMinus1: 5,
    frameHeightBitsMinus1: 3,
    enableSuperres: true,
    numPlanes: 3,
    separateUvDeltaQ: false,
    enableCdef: false,
    enableRestoration: false,
    subsamplingX: 1,
    subsamplingY: 1,
    filmGrainParamsPresent: true,
    enableOrderHint: false,
    frameIsIntra: true,
    showFrame: false,
    allowScreenContentTools: false,
    forceIntegerMv: 1,
    orderHint: 0,
    frameWidth: 39,
    frameHeight: 10,
    baseQIdx: 50,
    codedLossless: false,
    loopFilterLevel0: 0,
    cdefBits: 0,
    usesLr: false,
    txMode: 1,
    reducedTxSet: false,
  ),
  (
    seqForceScreenContentTools: 2,
    seqForceIntegerMv: 1,
    orderHintBits: 0,
    frameWidthBitsMinus1: 5,
    frameHeightBitsMinus1: 3,
    enableSuperres: false,
    numPlanes: 3,
    separateUvDeltaQ: false,
    enableCdef: true,
    enableRestoration: false,
    subsamplingX: 1,
    subsamplingY: 1,
    filmGrainParamsPresent: true,
    enableOrderHint: false,
    frameIsIntra: true,
    showFrame: true,
    allowScreenContentTools: true,
    forceIntegerMv: 1,
    orderHint: 0,
    frameWidth: 42,
    frameHeight: 7,
    baseQIdx: 232,
    codedLossless: false,
    loopFilterLevel0: 57,
    cdefBits: 2,
    usesLr: false,
    txMode: 1,
    reducedTxSet: false,
  ),
  (
    seqForceScreenContentTools: 2,
    seqForceIntegerMv: 0,
    orderHintBits: 0,
    frameWidthBitsMinus1: 3,
    frameHeightBitsMinus1: 3,
    enableSuperres: false,
    numPlanes: 3,
    separateUvDeltaQ: true,
    enableCdef: false,
    enableRestoration: true,
    subsamplingX: 1,
    subsamplingY: 1,
    filmGrainParamsPresent: true,
    enableOrderHint: false,
    frameIsIntra: true,
    showFrame: false,
    allowScreenContentTools: false,
    forceIntegerMv: 1,
    orderHint: 0,
    frameWidth: 15,
    frameHeight: 13,
    baseQIdx: 241,
    codedLossless: false,
    loopFilterLevel0: 4,
    cdefBits: 0,
    usesLr: true,
    txMode: 1,
    reducedTxSet: false,
  ),
  (
    seqForceScreenContentTools: 1,
    seqForceIntegerMv: 0,
    orderHintBits: 0,
    frameWidthBitsMinus1: 6,
    frameHeightBitsMinus1: 6,
    enableSuperres: true,
    numPlanes: 3,
    separateUvDeltaQ: true,
    enableCdef: false,
    enableRestoration: false,
    subsamplingX: 1,
    subsamplingY: 1,
    filmGrainParamsPresent: false,
    enableOrderHint: false,
    frameIsIntra: true,
    showFrame: false,
    allowScreenContentTools: true,
    forceIntegerMv: 1,
    orderHint: 0,
    frameWidth: 38,
    frameHeight: 45,
    baseQIdx: 196,
    codedLossless: false,
    loopFilterLevel0: 0,
    cdefBits: 0,
    usesLr: false,
    txMode: 1,
    reducedTxSet: true,
  ),
  (
    seqForceScreenContentTools: 1,
    seqForceIntegerMv: 2,
    orderHintBits: 0,
    frameWidthBitsMinus1: 5,
    frameHeightBitsMinus1: 5,
    enableSuperres: false,
    numPlanes: 3,
    separateUvDeltaQ: true,
    enableCdef: false,
    enableRestoration: false,
    subsamplingX: 1,
    subsamplingY: 1,
    filmGrainParamsPresent: false,
    enableOrderHint: false,
    frameIsIntra: true,
    showFrame: false,
    allowScreenContentTools: true,
    forceIntegerMv: 1,
    orderHint: 0,
    frameWidth: 59,
    frameHeight: 34,
    baseQIdx: 235,
    codedLossless: false,
    loopFilterLevel0: 29,
    cdefBits: 0,
    usesLr: false,
    txMode: 2,
    reducedTxSet: true,
  ),
  (
    seqForceScreenContentTools: 2,
    seqForceIntegerMv: 0,
    orderHintBits: 2,
    frameWidthBitsMinus1: 4,
    frameHeightBitsMinus1: 6,
    enableSuperres: false,
    numPlanes: 3,
    separateUvDeltaQ: false,
    enableCdef: true,
    enableRestoration: false,
    subsamplingX: 1,
    subsamplingY: 1,
    filmGrainParamsPresent: false,
    enableOrderHint: true,
    frameIsIntra: true,
    showFrame: true,
    allowScreenContentTools: true,
    forceIntegerMv: 1,
    orderHint: 3,
    frameWidth: 28,
    frameHeight: 55,
    baseQIdx: 64,
    codedLossless: false,
    loopFilterLevel0: 38,
    cdefBits: 1,
    usesLr: false,
    txMode: 2,
    reducedTxSet: false,
  ),
  (
    seqForceScreenContentTools: 2,
    seqForceIntegerMv: 2,
    orderHintBits: 0,
    frameWidthBitsMinus1: 5,
    frameHeightBitsMinus1: 4,
    enableSuperres: false,
    numPlanes: 3,
    separateUvDeltaQ: false,
    enableCdef: false,
    enableRestoration: false,
    subsamplingX: 1,
    subsamplingY: 1,
    filmGrainParamsPresent: false,
    enableOrderHint: false,
    frameIsIntra: true,
    showFrame: false,
    allowScreenContentTools: false,
    forceIntegerMv: 1,
    orderHint: 0,
    frameWidth: 1,
    frameHeight: 4,
    baseQIdx: 99,
    codedLossless: false,
    loopFilterLevel0: 37,
    cdefBits: 0,
    usesLr: false,
    txMode: 2,
    reducedTxSet: true,
  ),
  (
    seqForceScreenContentTools: 1,
    seqForceIntegerMv: 2,
    orderHintBits: 0,
    frameWidthBitsMinus1: 6,
    frameHeightBitsMinus1: 3,
    enableSuperres: false,
    numPlanes: 3,
    separateUvDeltaQ: false,
    enableCdef: false,
    enableRestoration: true,
    subsamplingX: 1,
    subsamplingY: 1,
    filmGrainParamsPresent: false,
    enableOrderHint: false,
    frameIsIntra: true,
    showFrame: false,
    allowScreenContentTools: true,
    forceIntegerMv: 1,
    orderHint: 0,
    frameWidth: 36,
    frameHeight: 12,
    baseQIdx: 127,
    codedLossless: false,
    loopFilterLevel0: 44,
    cdefBits: 0,
    usesLr: true,
    txMode: 2,
    reducedTxSet: true,
  ),
  (
    seqForceScreenContentTools: 1,
    seqForceIntegerMv: 2,
    orderHintBits: 0,
    frameWidthBitsMinus1: 4,
    frameHeightBitsMinus1: 6,
    enableSuperres: true,
    numPlanes: 3,
    separateUvDeltaQ: true,
    enableCdef: true,
    enableRestoration: false,
    subsamplingX: 1,
    subsamplingY: 1,
    filmGrainParamsPresent: true,
    enableOrderHint: false,
    frameIsIntra: true,
    showFrame: true,
    allowScreenContentTools: true,
    forceIntegerMv: 1,
    orderHint: 0,
    frameWidth: 5,
    frameHeight: 3,
    baseQIdx: 34,
    codedLossless: false,
    loopFilterLevel0: 17,
    cdefBits: 2,
    usesLr: false,
    txMode: 2,
    reducedTxSet: true,
  ),
  (
    seqForceScreenContentTools: 1,
    seqForceIntegerMv: 2,
    orderHintBits: 7,
    frameWidthBitsMinus1: 3,
    frameHeightBitsMinus1: 3,
    enableSuperres: false,
    numPlanes: 3,
    separateUvDeltaQ: true,
    enableCdef: false,
    enableRestoration: false,
    subsamplingX: 1,
    subsamplingY: 1,
    filmGrainParamsPresent: true,
    enableOrderHint: true,
    frameIsIntra: true,
    showFrame: false,
    allowScreenContentTools: true,
    forceIntegerMv: 1,
    orderHint: 22,
    frameWidth: 14,
    frameHeight: 11,
    baseQIdx: 232,
    codedLossless: false,
    loopFilterLevel0: 28,
    cdefBits: 0,
    usesLr: false,
    txMode: 1,
    reducedTxSet: true,
  ),
  (
    seqForceScreenContentTools: 1,
    seqForceIntegerMv: 2,
    orderHintBits: 7,
    frameWidthBitsMinus1: 4,
    frameHeightBitsMinus1: 3,
    enableSuperres: false,
    numPlanes: 3,
    separateUvDeltaQ: false,
    enableCdef: true,
    enableRestoration: true,
    subsamplingX: 1,
    subsamplingY: 1,
    filmGrainParamsPresent: true,
    enableOrderHint: true,
    frameIsIntra: true,
    showFrame: false,
    allowScreenContentTools: true,
    forceIntegerMv: 1,
    orderHint: 96,
    frameWidth: 25,
    frameHeight: 4,
    baseQIdx: 246,
    codedLossless: false,
    loopFilterLevel0: 0,
    cdefBits: 0,
    usesLr: false,
    txMode: 1,
    reducedTxSet: true,
  ),
  (
    seqForceScreenContentTools: 1,
    seqForceIntegerMv: 2,
    orderHintBits: 3,
    frameWidthBitsMinus1: 6,
    frameHeightBitsMinus1: 5,
    enableSuperres: true,
    numPlanes: 3,
    separateUvDeltaQ: false,
    enableCdef: false,
    enableRestoration: true,
    subsamplingX: 1,
    subsamplingY: 1,
    filmGrainParamsPresent: false,
    enableOrderHint: true,
    frameIsIntra: true,
    showFrame: false,
    allowScreenContentTools: true,
    forceIntegerMv: 1,
    orderHint: 6,
    frameWidth: 16,
    frameHeight: 4,
    baseQIdx: 8,
    codedLossless: false,
    loopFilterLevel0: 36,
    cdefBits: 0,
    usesLr: true,
    txMode: 1,
    reducedTxSet: false,
  ),
  (
    seqForceScreenContentTools: 2,
    seqForceIntegerMv: 0,
    orderHintBits: 8,
    frameWidthBitsMinus1: 4,
    frameHeightBitsMinus1: 5,
    enableSuperres: false,
    numPlanes: 3,
    separateUvDeltaQ: false,
    enableCdef: true,
    enableRestoration: false,
    subsamplingX: 1,
    subsamplingY: 1,
    filmGrainParamsPresent: true,
    enableOrderHint: true,
    frameIsIntra: true,
    showFrame: false,
    allowScreenContentTools: false,
    forceIntegerMv: 1,
    orderHint: 247,
    frameWidth: 16,
    frameHeight: 51,
    baseQIdx: 0,
    codedLossless: true,
    loopFilterLevel0: 0,
    cdefBits: 0,
    usesLr: false,
    txMode: 0,
    reducedTxSet: false,
  ),
  (
    seqForceScreenContentTools: 0,
    seqForceIntegerMv: 2,
    orderHintBits: 5,
    frameWidthBitsMinus1: 5,
    frameHeightBitsMinus1: 6,
    enableSuperres: false,
    numPlanes: 3,
    separateUvDeltaQ: false,
    enableCdef: true,
    enableRestoration: true,
    subsamplingX: 1,
    subsamplingY: 1,
    filmGrainParamsPresent: false,
    enableOrderHint: true,
    frameIsIntra: true,
    showFrame: true,
    allowScreenContentTools: false,
    forceIntegerMv: 1,
    orderHint: 21,
    frameWidth: 41,
    frameHeight: 35,
    baseQIdx: 184,
    codedLossless: false,
    loopFilterLevel0: 37,
    cdefBits: 1,
    usesLr: true,
    txMode: 1,
    reducedTxSet: true,
  ),
  (
    seqForceScreenContentTools: 2,
    seqForceIntegerMv: 2,
    orderHintBits: 1,
    frameWidthBitsMinus1: 4,
    frameHeightBitsMinus1: 4,
    enableSuperres: false,
    numPlanes: 3,
    separateUvDeltaQ: false,
    enableCdef: false,
    enableRestoration: true,
    subsamplingX: 1,
    subsamplingY: 1,
    filmGrainParamsPresent: true,
    enableOrderHint: true,
    frameIsIntra: true,
    showFrame: false,
    allowScreenContentTools: true,
    forceIntegerMv: 1,
    orderHint: 0,
    frameWidth: 12,
    frameHeight: 2,
    baseQIdx: 0,
    codedLossless: true,
    loopFilterLevel0: 0,
    cdefBits: 0,
    usesLr: false,
    txMode: 0,
    reducedTxSet: false,
  ),
  (
    seqForceScreenContentTools: 1,
    seqForceIntegerMv: 2,
    orderHintBits: 7,
    frameWidthBitsMinus1: 4,
    frameHeightBitsMinus1: 3,
    enableSuperres: true,
    numPlanes: 3,
    separateUvDeltaQ: false,
    enableCdef: true,
    enableRestoration: true,
    subsamplingX: 1,
    subsamplingY: 1,
    filmGrainParamsPresent: true,
    enableOrderHint: true,
    frameIsIntra: true,
    showFrame: false,
    allowScreenContentTools: true,
    forceIntegerMv: 1,
    orderHint: 105,
    frameWidth: 5,
    frameHeight: 7,
    baseQIdx: 41,
    codedLossless: false,
    loopFilterLevel0: 0,
    cdefBits: 0,
    usesLr: false,
    txMode: 2,
    reducedTxSet: false,
  ),
  (
    seqForceScreenContentTools: 2,
    seqForceIntegerMv: 0,
    orderHintBits: 7,
    frameWidthBitsMinus1: 5,
    frameHeightBitsMinus1: 6,
    enableSuperres: false,
    numPlanes: 3,
    separateUvDeltaQ: true,
    enableCdef: true,
    enableRestoration: false,
    subsamplingX: 1,
    subsamplingY: 1,
    filmGrainParamsPresent: true,
    enableOrderHint: true,
    frameIsIntra: true,
    showFrame: false,
    allowScreenContentTools: true,
    forceIntegerMv: 1,
    orderHint: 91,
    frameWidth: 21,
    frameHeight: 32,
    baseQIdx: 124,
    codedLossless: false,
    loopFilterLevel0: 0,
    cdefBits: 0,
    usesLr: false,
    txMode: 1,
    reducedTxSet: true,
  ),
  (
    seqForceScreenContentTools: 1,
    seqForceIntegerMv: 1,
    orderHintBits: 0,
    frameWidthBitsMinus1: 6,
    frameHeightBitsMinus1: 6,
    enableSuperres: false,
    numPlanes: 3,
    separateUvDeltaQ: false,
    enableCdef: false,
    enableRestoration: false,
    subsamplingX: 1,
    subsamplingY: 1,
    filmGrainParamsPresent: true,
    enableOrderHint: false,
    frameIsIntra: true,
    showFrame: false,
    allowScreenContentTools: true,
    forceIntegerMv: 1,
    orderHint: 0,
    frameWidth: 26,
    frameHeight: 1,
    baseQIdx: 74,
    codedLossless: false,
    loopFilterLevel0: 0,
    cdefBits: 0,
    usesLr: false,
    txMode: 1,
    reducedTxSet: true,
  ),
  (
    seqForceScreenContentTools: 2,
    seqForceIntegerMv: 2,
    orderHintBits: 0,
    frameWidthBitsMinus1: 3,
    frameHeightBitsMinus1: 4,
    enableSuperres: false,
    numPlanes: 3,
    separateUvDeltaQ: true,
    enableCdef: true,
    enableRestoration: true,
    subsamplingX: 1,
    subsamplingY: 1,
    filmGrainParamsPresent: false,
    enableOrderHint: false,
    frameIsIntra: true,
    showFrame: true,
    allowScreenContentTools: false,
    forceIntegerMv: 1,
    orderHint: 0,
    frameWidth: 13,
    frameHeight: 18,
    baseQIdx: 78,
    codedLossless: false,
    loopFilterLevel0: 51,
    cdefBits: 3,
    usesLr: true,
    txMode: 1,
    reducedTxSet: false,
  ),
  (
    seqForceScreenContentTools: 2,
    seqForceIntegerMv: 2,
    orderHintBits: 0,
    frameWidthBitsMinus1: 4,
    frameHeightBitsMinus1: 4,
    enableSuperres: false,
    numPlanes: 3,
    separateUvDeltaQ: false,
    enableCdef: true,
    enableRestoration: true,
    subsamplingX: 1,
    subsamplingY: 1,
    filmGrainParamsPresent: true,
    enableOrderHint: false,
    frameIsIntra: true,
    showFrame: true,
    allowScreenContentTools: true,
    forceIntegerMv: 1,
    orderHint: 0,
    frameWidth: 11,
    frameHeight: 29,
    baseQIdx: 63,
    codedLossless: false,
    loopFilterLevel0: 0,
    cdefBits: 0,
    usesLr: false,
    txMode: 1,
    reducedTxSet: true,
  ),
  (
    seqForceScreenContentTools: 0,
    seqForceIntegerMv: 2,
    orderHintBits: 2,
    frameWidthBitsMinus1: 5,
    frameHeightBitsMinus1: 5,
    enableSuperres: true,
    numPlanes: 3,
    separateUvDeltaQ: false,
    enableCdef: false,
    enableRestoration: true,
    subsamplingX: 1,
    subsamplingY: 1,
    filmGrainParamsPresent: false,
    enableOrderHint: true,
    frameIsIntra: true,
    showFrame: false,
    allowScreenContentTools: false,
    forceIntegerMv: 1,
    orderHint: 3,
    frameWidth: 61,
    frameHeight: 38,
    baseQIdx: 126,
    codedLossless: false,
    loopFilterLevel0: 63,
    cdefBits: 0,
    usesLr: true,
    txMode: 2,
    reducedTxSet: true,
  ),
  (
    seqForceScreenContentTools: 2,
    seqForceIntegerMv: 2,
    orderHintBits: 0,
    frameWidthBitsMinus1: 3,
    frameHeightBitsMinus1: 6,
    enableSuperres: true,
    numPlanes: 3,
    separateUvDeltaQ: false,
    enableCdef: false,
    enableRestoration: true,
    subsamplingX: 1,
    subsamplingY: 1,
    filmGrainParamsPresent: false,
    enableOrderHint: false,
    frameIsIntra: true,
    showFrame: false,
    allowScreenContentTools: true,
    forceIntegerMv: 1,
    orderHint: 0,
    frameWidth: 8,
    frameHeight: 3,
    baseQIdx: 0,
    codedLossless: true,
    loopFilterLevel0: 0,
    cdefBits: 0,
    usesLr: false,
    txMode: 0,
    reducedTxSet: true,
  ),
  (
    seqForceScreenContentTools: 1,
    seqForceIntegerMv: 0,
    orderHintBits: 0,
    frameWidthBitsMinus1: 3,
    frameHeightBitsMinus1: 4,
    enableSuperres: false,
    numPlanes: 3,
    separateUvDeltaQ: true,
    enableCdef: false,
    enableRestoration: false,
    subsamplingX: 1,
    subsamplingY: 1,
    filmGrainParamsPresent: true,
    enableOrderHint: false,
    frameIsIntra: true,
    showFrame: true,
    allowScreenContentTools: true,
    forceIntegerMv: 1,
    orderHint: 0,
    frameWidth: 13,
    frameHeight: 8,
    baseQIdx: 234,
    codedLossless: false,
    loopFilterLevel0: 52,
    cdefBits: 0,
    usesLr: false,
    txMode: 1,
    reducedTxSet: false,
  ),
  (
    seqForceScreenContentTools: 2,
    seqForceIntegerMv: 0,
    orderHintBits: 3,
    frameWidthBitsMinus1: 6,
    frameHeightBitsMinus1: 5,
    enableSuperres: true,
    numPlanes: 3,
    separateUvDeltaQ: true,
    enableCdef: true,
    enableRestoration: false,
    subsamplingX: 1,
    subsamplingY: 1,
    filmGrainParamsPresent: true,
    enableOrderHint: true,
    frameIsIntra: true,
    showFrame: true,
    allowScreenContentTools: true,
    forceIntegerMv: 1,
    orderHint: 7,
    frameWidth: 2,
    frameHeight: 60,
    baseQIdx: 208,
    codedLossless: false,
    loopFilterLevel0: 0,
    cdefBits: 0,
    usesLr: false,
    txMode: 1,
    reducedTxSet: false,
  ),
  (
    seqForceScreenContentTools: 1,
    seqForceIntegerMv: 2,
    orderHintBits: 0,
    frameWidthBitsMinus1: 6,
    frameHeightBitsMinus1: 3,
    enableSuperres: false,
    numPlanes: 3,
    separateUvDeltaQ: true,
    enableCdef: true,
    enableRestoration: false,
    subsamplingX: 1,
    subsamplingY: 1,
    filmGrainParamsPresent: false,
    enableOrderHint: false,
    frameIsIntra: true,
    showFrame: true,
    allowScreenContentTools: true,
    forceIntegerMv: 1,
    orderHint: 0,
    frameWidth: 19,
    frameHeight: 10,
    baseQIdx: 0,
    codedLossless: true,
    loopFilterLevel0: 0,
    cdefBits: 0,
    usesLr: false,
    txMode: 0,
    reducedTxSet: false,
  ),
  (
    seqForceScreenContentTools: 0,
    seqForceIntegerMv: 2,
    orderHintBits: 0,
    frameWidthBitsMinus1: 6,
    frameHeightBitsMinus1: 3,
    enableSuperres: false,
    numPlanes: 3,
    separateUvDeltaQ: true,
    enableCdef: false,
    enableRestoration: false,
    subsamplingX: 1,
    subsamplingY: 1,
    filmGrainParamsPresent: true,
    enableOrderHint: false,
    frameIsIntra: true,
    showFrame: true,
    allowScreenContentTools: false,
    forceIntegerMv: 1,
    orderHint: 0,
    frameWidth: 51,
    frameHeight: 13,
    baseQIdx: 145,
    codedLossless: false,
    loopFilterLevel0: 58,
    cdefBits: 0,
    usesLr: false,
    txMode: 1,
    reducedTxSet: true,
  ),
  (
    seqForceScreenContentTools: 1,
    seqForceIntegerMv: 2,
    orderHintBits: 7,
    frameWidthBitsMinus1: 3,
    frameHeightBitsMinus1: 6,
    enableSuperres: false,
    numPlanes: 3,
    separateUvDeltaQ: false,
    enableCdef: true,
    enableRestoration: true,
    subsamplingX: 1,
    subsamplingY: 1,
    filmGrainParamsPresent: true,
    enableOrderHint: true,
    frameIsIntra: true,
    showFrame: false,
    allowScreenContentTools: true,
    forceIntegerMv: 1,
    orderHint: 35,
    frameWidth: 11,
    frameHeight: 1,
    baseQIdx: 252,
    codedLossless: false,
    loopFilterLevel0: 0,
    cdefBits: 0,
    usesLr: false,
    txMode: 1,
    reducedTxSet: true,
  ),
  (
    seqForceScreenContentTools: 2,
    seqForceIntegerMv: 0,
    orderHintBits: 0,
    frameWidthBitsMinus1: 4,
    frameHeightBitsMinus1: 3,
    enableSuperres: false,
    numPlanes: 3,
    separateUvDeltaQ: true,
    enableCdef: true,
    enableRestoration: false,
    subsamplingX: 1,
    subsamplingY: 1,
    filmGrainParamsPresent: true,
    enableOrderHint: false,
    frameIsIntra: true,
    showFrame: false,
    allowScreenContentTools: true,
    forceIntegerMv: 1,
    orderHint: 0,
    frameWidth: 21,
    frameHeight: 2,
    baseQIdx: 162,
    codedLossless: false,
    loopFilterLevel0: 0,
    cdefBits: 0,
    usesLr: false,
    txMode: 2,
    reducedTxSet: true,
  ),
  (
    seqForceScreenContentTools: 2,
    seqForceIntegerMv: 1,
    orderHintBits: 8,
    frameWidthBitsMinus1: 5,
    frameHeightBitsMinus1: 3,
    enableSuperres: true,
    numPlanes: 3,
    separateUvDeltaQ: true,
    enableCdef: true,
    enableRestoration: false,
    subsamplingX: 1,
    subsamplingY: 1,
    filmGrainParamsPresent: false,
    enableOrderHint: true,
    frameIsIntra: true,
    showFrame: true,
    allowScreenContentTools: true,
    forceIntegerMv: 1,
    orderHint: 111,
    frameWidth: 39,
    frameHeight: 13,
    baseQIdx: 64,
    codedLossless: false,
    loopFilterLevel0: 15,
    cdefBits: 0,
    usesLr: false,
    txMode: 1,
    reducedTxSet: false,
  ),
  (
    seqForceScreenContentTools: 0,
    seqForceIntegerMv: 2,
    orderHintBits: 8,
    frameWidthBitsMinus1: 6,
    frameHeightBitsMinus1: 5,
    enableSuperres: true,
    numPlanes: 3,
    separateUvDeltaQ: false,
    enableCdef: false,
    enableRestoration: true,
    subsamplingX: 1,
    subsamplingY: 1,
    filmGrainParamsPresent: false,
    enableOrderHint: true,
    frameIsIntra: true,
    showFrame: false,
    allowScreenContentTools: false,
    forceIntegerMv: 1,
    orderHint: 101,
    frameWidth: 10,
    frameHeight: 34,
    baseQIdx: 236,
    codedLossless: false,
    loopFilterLevel0: 41,
    cdefBits: 0,
    usesLr: false,
    txMode: 1,
    reducedTxSet: true,
  ),
  (
    seqForceScreenContentTools: 2,
    seqForceIntegerMv: 0,
    orderHintBits: 4,
    frameWidthBitsMinus1: 4,
    frameHeightBitsMinus1: 5,
    enableSuperres: true,
    numPlanes: 3,
    separateUvDeltaQ: false,
    enableCdef: false,
    enableRestoration: false,
    subsamplingX: 1,
    subsamplingY: 1,
    filmGrainParamsPresent: false,
    enableOrderHint: true,
    frameIsIntra: true,
    showFrame: true,
    allowScreenContentTools: true,
    forceIntegerMv: 1,
    orderHint: 9,
    frameWidth: 2,
    frameHeight: 42,
    baseQIdx: 196,
    codedLossless: false,
    loopFilterLevel0: 49,
    cdefBits: 0,
    usesLr: false,
    txMode: 1,
    reducedTxSet: true,
  ),
  (
    seqForceScreenContentTools: 0,
    seqForceIntegerMv: 2,
    orderHintBits: 4,
    frameWidthBitsMinus1: 6,
    frameHeightBitsMinus1: 6,
    enableSuperres: false,
    numPlanes: 3,
    separateUvDeltaQ: false,
    enableCdef: true,
    enableRestoration: false,
    subsamplingX: 1,
    subsamplingY: 1,
    filmGrainParamsPresent: false,
    enableOrderHint: true,
    frameIsIntra: true,
    showFrame: false,
    allowScreenContentTools: false,
    forceIntegerMv: 1,
    orderHint: 1,
    frameWidth: 41,
    frameHeight: 44,
    baseQIdx: 238,
    codedLossless: false,
    loopFilterLevel0: 21,
    cdefBits: 3,
    usesLr: false,
    txMode: 2,
    reducedTxSet: true,
  ),
  (
    seqForceScreenContentTools: 2,
    seqForceIntegerMv: 1,
    orderHintBits: 0,
    frameWidthBitsMinus1: 5,
    frameHeightBitsMinus1: 5,
    enableSuperres: true,
    numPlanes: 3,
    separateUvDeltaQ: false,
    enableCdef: false,
    enableRestoration: false,
    subsamplingX: 1,
    subsamplingY: 1,
    filmGrainParamsPresent: false,
    enableOrderHint: false,
    frameIsIntra: true,
    showFrame: false,
    allowScreenContentTools: false,
    forceIntegerMv: 1,
    orderHint: 0,
    frameWidth: 17,
    frameHeight: 25,
    baseQIdx: 169,
    codedLossless: false,
    loopFilterLevel0: 13,
    cdefBits: 0,
    usesLr: false,
    txMode: 1,
    reducedTxSet: false,
  ),
  (
    seqForceScreenContentTools: 2,
    seqForceIntegerMv: 2,
    orderHintBits: 1,
    frameWidthBitsMinus1: 5,
    frameHeightBitsMinus1: 4,
    enableSuperres: false,
    numPlanes: 3,
    separateUvDeltaQ: true,
    enableCdef: true,
    enableRestoration: false,
    subsamplingX: 1,
    subsamplingY: 1,
    filmGrainParamsPresent: false,
    enableOrderHint: true,
    frameIsIntra: true,
    showFrame: true,
    allowScreenContentTools: true,
    forceIntegerMv: 1,
    orderHint: 0,
    frameWidth: 17,
    frameHeight: 16,
    baseQIdx: 0,
    codedLossless: true,
    loopFilterLevel0: 0,
    cdefBits: 0,
    usesLr: false,
    txMode: 0,
    reducedTxSet: false,
  ),
  (
    seqForceScreenContentTools: 2,
    seqForceIntegerMv: 2,
    orderHintBits: 7,
    frameWidthBitsMinus1: 4,
    frameHeightBitsMinus1: 4,
    enableSuperres: false,
    numPlanes: 3,
    separateUvDeltaQ: false,
    enableCdef: false,
    enableRestoration: true,
    subsamplingX: 1,
    subsamplingY: 1,
    filmGrainParamsPresent: true,
    enableOrderHint: true,
    frameIsIntra: true,
    showFrame: false,
    allowScreenContentTools: true,
    forceIntegerMv: 1,
    orderHint: 90,
    frameWidth: 2,
    frameHeight: 26,
    baseQIdx: 98,
    codedLossless: false,
    loopFilterLevel0: 0,
    cdefBits: 0,
    usesLr: false,
    txMode: 1,
    reducedTxSet: false,
  ),
  (
    seqForceScreenContentTools: 1,
    seqForceIntegerMv: 2,
    orderHintBits: 1,
    frameWidthBitsMinus1: 4,
    frameHeightBitsMinus1: 3,
    enableSuperres: false,
    numPlanes: 3,
    separateUvDeltaQ: true,
    enableCdef: false,
    enableRestoration: true,
    subsamplingX: 1,
    subsamplingY: 1,
    filmGrainParamsPresent: false,
    enableOrderHint: true,
    frameIsIntra: true,
    showFrame: false,
    allowScreenContentTools: true,
    forceIntegerMv: 1,
    orderHint: 0,
    frameWidth: 13,
    frameHeight: 13,
    baseQIdx: 222,
    codedLossless: false,
    loopFilterLevel0: 28,
    cdefBits: 0,
    usesLr: true,
    txMode: 2,
    reducedTxSet: false,
  ),
  (
    seqForceScreenContentTools: 2,
    seqForceIntegerMv: 1,
    orderHintBits: 4,
    frameWidthBitsMinus1: 6,
    frameHeightBitsMinus1: 4,
    enableSuperres: false,
    numPlanes: 3,
    separateUvDeltaQ: true,
    enableCdef: true,
    enableRestoration: true,
    subsamplingX: 1,
    subsamplingY: 1,
    filmGrainParamsPresent: true,
    enableOrderHint: true,
    frameIsIntra: true,
    showFrame: false,
    allowScreenContentTools: true,
    forceIntegerMv: 1,
    orderHint: 10,
    frameWidth: 34,
    frameHeight: 29,
    baseQIdx: 113,
    codedLossless: false,
    loopFilterLevel0: 27,
    cdefBits: 3,
    usesLr: true,
    txMode: 1,
    reducedTxSet: true,
  ),
  (
    seqForceScreenContentTools: 1,
    seqForceIntegerMv: 2,
    orderHintBits: 5,
    frameWidthBitsMinus1: 3,
    frameHeightBitsMinus1: 6,
    enableSuperres: true,
    numPlanes: 3,
    separateUvDeltaQ: false,
    enableCdef: false,
    enableRestoration: true,
    subsamplingX: 1,
    subsamplingY: 1,
    filmGrainParamsPresent: false,
    enableOrderHint: true,
    frameIsIntra: true,
    showFrame: true,
    allowScreenContentTools: true,
    forceIntegerMv: 1,
    orderHint: 2,
    frameWidth: 12,
    frameHeight: 24,
    baseQIdx: 27,
    codedLossless: false,
    loopFilterLevel0: 0,
    cdefBits: 0,
    usesLr: false,
    txMode: 1,
    reducedTxSet: false,
  ),
  (
    seqForceScreenContentTools: 0,
    seqForceIntegerMv: 2,
    orderHintBits: 0,
    frameWidthBitsMinus1: 3,
    frameHeightBitsMinus1: 5,
    enableSuperres: false,
    numPlanes: 3,
    separateUvDeltaQ: true,
    enableCdef: false,
    enableRestoration: false,
    subsamplingX: 1,
    subsamplingY: 1,
    filmGrainParamsPresent: true,
    enableOrderHint: false,
    frameIsIntra: true,
    showFrame: false,
    allowScreenContentTools: false,
    forceIntegerMv: 1,
    orderHint: 0,
    frameWidth: 8,
    frameHeight: 22,
    baseQIdx: 149,
    codedLossless: false,
    loopFilterLevel0: 38,
    cdefBits: 0,
    usesLr: false,
    txMode: 1,
    reducedTxSet: true,
  ),
  (
    seqForceScreenContentTools: 0,
    seqForceIntegerMv: 2,
    orderHintBits: 7,
    frameWidthBitsMinus1: 6,
    frameHeightBitsMinus1: 5,
    enableSuperres: true,
    numPlanes: 3,
    separateUvDeltaQ: true,
    enableCdef: true,
    enableRestoration: false,
    subsamplingX: 1,
    subsamplingY: 1,
    filmGrainParamsPresent: true,
    enableOrderHint: true,
    frameIsIntra: true,
    showFrame: false,
    allowScreenContentTools: false,
    forceIntegerMv: 1,
    orderHint: 31,
    frameWidth: 63,
    frameHeight: 38,
    baseQIdx: 74,
    codedLossless: false,
    loopFilterLevel0: 57,
    cdefBits: 2,
    usesLr: false,
    txMode: 1,
    reducedTxSet: false,
  ),
  (
    seqForceScreenContentTools: 1,
    seqForceIntegerMv: 2,
    orderHintBits: 2,
    frameWidthBitsMinus1: 6,
    frameHeightBitsMinus1: 3,
    enableSuperres: false,
    numPlanes: 3,
    separateUvDeltaQ: true,
    enableCdef: false,
    enableRestoration: false,
    subsamplingX: 1,
    subsamplingY: 1,
    filmGrainParamsPresent: true,
    enableOrderHint: true,
    frameIsIntra: true,
    showFrame: false,
    allowScreenContentTools: true,
    forceIntegerMv: 1,
    orderHint: 2,
    frameWidth: 36,
    frameHeight: 11,
    baseQIdx: 118,
    codedLossless: false,
    loopFilterLevel0: 0,
    cdefBits: 0,
    usesLr: false,
    txMode: 2,
    reducedTxSet: true,
  ),
];

class _W {
  final bits = <int>[];
  void f(int value, int n) {
    for (var k = n - 1; k >= 0; k--) {
      bits.add((value >> k) & 1);
    }
  }

  int get len => bits.length;

  List<int> toBytes(int len) {
    final out = List.filled(len, 0);
    for (var i = 0; i < bits.length && i < len * 8; i++) {
      if (bits[i] != 0) out[i >> 3] |= 1 << (7 - (i & 7));
    }
    return out;
  }
}

const _selScreen = 2;
const _selIntMv = 2;

// A complete non-reduced keyframe-friendly sequence_header_obu payload: profile
// 0, 8-bit 4:2:0, no timing / decoder model / frame ids, one operating point,
// single-superblock max frame size.
List<int> _seqBytes(Random rng) {
  final w = _W();
  bool b() => rng.nextBool();
  w.f(0, 3); // seq_profile = 0
  w.f(0, 1); // still_picture
  w.f(0, 1); // reduced_still_picture_header = 0
  w.f(0, 1); // timing_info_present_flag = 0
  w.f(0, 1); // initial_display_delay_present_flag = 0
  w.f(0, 5); // operating_points_cnt_minus_1 = 0
  w.f(rng.nextInt(1 << 12), 12); // operating_point_idc[0]
  w.f(rng.nextInt(8), 5); // seq_level_idx[0] (<= 7 => no seq_tier)
  final wb = rng.nextInt(4) + 3, hb = rng.nextInt(4) + 3;
  w.f(wb, 4); // frame_width_bits_minus_1
  w.f(hb, 4); // frame_height_bits_minus_1
  w.f(rng.nextInt(64), wb + 1); // max_frame_width_minus_1 (<= 63 => single SB)
  w.f(rng.nextInt(64), hb + 1); // max_frame_height_minus_1
  w.f(0, 1); // frame_id_numbers_present_flag = 0
  w.f(0, 1); // use_128x128_superblock = 0
  w.f(b() ? 1 : 0, 1); // enable_filter_intra
  w.f(b() ? 1 : 0, 1); // enable_intra_edge_filter
  w.f(b() ? 1 : 0, 1); // enable_interintra_compound
  w.f(b() ? 1 : 0, 1); // enable_masked_compound
  w.f(b() ? 1 : 0, 1); // enable_warped_motion
  w.f(b() ? 1 : 0, 1); // enable_dual_filter
  final orderHint = b();
  w.f(orderHint ? 1 : 0, 1); // enable_order_hint
  if (orderHint) {
    w.f(b() ? 1 : 0, 1); // enable_jnt_comp
    w.f(b() ? 1 : 0, 1); // enable_ref_frame_mvs
  }
  final chooseScreen = b();
  w.f(chooseScreen ? 1 : 0, 1);
  var forceScreen = 2;
  if (!chooseScreen) {
    forceScreen = rng.nextInt(2);
    w.f(forceScreen, 1);
  }
  if (forceScreen > 0) {
    final chooseIntMv = b();
    w.f(chooseIntMv ? 1 : 0, 1);
    if (!chooseIntMv) w.f(rng.nextInt(2), 1);
  }
  if (orderHint) w.f(rng.nextInt(8), 3); // order_hint_bits_minus_1
  w.f(b() ? 1 : 0, 1); // enable_superres
  w.f(b() ? 1 : 0, 1); // enable_cdef
  w.f(b() ? 1 : 0, 1); // enable_restoration
  // color_config (profile 0, 8-bit, 4:2:0)
  w.f(0, 1); // high_bitdepth = 0
  w.f(0, 1); // mono_chrome = 0
  w.f(0, 1); // color_description_present_flag = 0
  w.f(b() ? 1 : 0, 1); // color_range
  w.f(rng.nextInt(4), 2); // chroma_sample_position (subX==subY==1)
  w.f(b() ? 1 : 0, 1); // separate_uv_delta_q
  w.f(b() ? 1 : 0, 1); // film_grain_params_present
  return w.toBytes(32);
}

// The keyframe frame header writer (mirrors SW parseFrameHeader through the full
// in-scope header). Returns (bytes, bitsConsumed).
(List<int>, int) _frameBytes(Random rng, _Seq s) {
  final w = _W();
  bool rb() => rng.nextBool();

  w.f(0, 1); // show_existing_frame = 0
  w.f(0, 2); // frame_type = KEY_FRAME (intra)
  final showFrame = rb();
  w.f(showFrame ? 1 : 0, 1);
  var showable = false;
  if (!showFrame) {
    showable = rb();
    w.f(showable ? 1 : 0, 1);
  }
  if (!showFrame) w.f(0, 1); // error_resilient_mode = 0
  final disableCdf = rb();
  w.f(disableCdf ? 1 : 0, 1);
  var allowScreen = s.seqForceScreenContentTools != 0;
  if (s.seqForceScreenContentTools == _selScreen) {
    allowScreen = rb();
    w.f(allowScreen ? 1 : 0, 1);
  }
  if (allowScreen && s.seqForceIntegerMv == _selIntMv) {
    w.f(rb() ? 1 : 0, 1);
  }
  final frameSizeOverride = rb();
  w.f(frameSizeOverride ? 1 : 0, 1);
  if (s.orderHintBits > 0)
    w.f(rng.nextInt(1 << s.orderHintBits), s.orderHintBits);
  if (!showFrame) w.f(rng.nextInt(256), 8);
  if (frameSizeOverride) {
    final wCap = (1 << (s.frameWidthBitsMinus1 + 1)) < 64
        ? (1 << (s.frameWidthBitsMinus1 + 1))
        : 64;
    final hCap = (1 << (s.frameHeightBitsMinus1 + 1)) < 64
        ? (1 << (s.frameHeightBitsMinus1 + 1))
        : 64;
    w.f(rng.nextInt(wCap), s.frameWidthBitsMinus1 + 1);
    w.f(rng.nextInt(hCap), s.frameHeightBitsMinus1 + 1);
  }
  if (s.enableSuperres) w.f(0, 1);
  final renderDiff = rb();
  w.f(renderDiff ? 1 : 0, 1);
  if (renderDiff) {
    w.f(rng.nextInt(1 << 16), 16);
    w.f(rng.nextInt(1 << 16), 16);
  }
  var allowIntrabc = false;
  if (allowScreen) {
    allowIntrabc = rb();
    w.f(allowIntrabc ? 1 : 0, 1);
  }
  if (!disableCdf) w.f(rb() ? 1 : 0, 1);
  w.f(1, 1); // tile_info uniform = 1 (single SB)
  final lossless = rng.nextInt(8) == 0;
  w.f(lossless ? 0 : (rng.nextInt(255) + 1), 8);
  void deltaQ() {
    if (!lossless && rb()) {
      w.f(1, 1);
      w.f(rng.nextInt(128), 7);
    } else {
      w.f(0, 1);
    }
  }

  deltaQ();
  if (s.numPlanes > 1) {
    var diffUv = false;
    if (s.separateUvDeltaQ) {
      diffUv = rb();
      w.f(diffUv ? 1 : 0, 1);
    }
    deltaQ();
    deltaQ();
    if (diffUv) {
      deltaQ();
      deltaQ();
    }
  }
  final usingQm = rb();
  w.f(usingQm ? 1 : 0, 1);
  if (usingQm) {
    w.f(rng.nextInt(16), 4);
    w.f(rng.nextInt(16), 4);
    if (s.separateUvDeltaQ) w.f(rng.nextInt(16), 4);
  }
  w.f(0, 1); // segmentation_enabled = 0
  var deltaQPresent = false;
  if (!lossless) {
    deltaQPresent = rb();
    w.f(deltaQPresent ? 1 : 0, 1);
    if (deltaQPresent) w.f(rng.nextInt(4), 2);
  }
  if (deltaQPresent && !allowIntrabc) {
    final deltaLfPresent = rb();
    w.f(deltaLfPresent ? 1 : 0, 1);
    if (deltaLfPresent) {
      w.f(rng.nextInt(4), 2);
      w.f(rb() ? 1 : 0, 1);
    }
  }
  if (!lossless && !allowIntrabc) {
    final lvl0 = rng.nextInt(64);
    final lvl1 = rng.nextInt(64);
    w.f(lvl0, 6);
    w.f(lvl1, 6);
    if (s.numPlanes > 1 && (lvl0 != 0 || lvl1 != 0)) {
      w.f(rng.nextInt(64), 6);
      w.f(rng.nextInt(64), 6);
    }
    w.f(rng.nextInt(8), 3);
    final deltaEnabled = rb();
    w.f(deltaEnabled ? 1 : 0, 1);
    if (deltaEnabled) {
      final update = rb();
      w.f(update ? 1 : 0, 1);
      if (update) {
        for (var i = 0; i < 8; i++) {
          if (rb()) {
            w.f(1, 1);
            w.f(rng.nextInt(128), 7);
          } else {
            w.f(0, 1);
          }
        }
        for (var i = 0; i < 2; i++) {
          if (rb()) {
            w.f(1, 1);
            w.f(rng.nextInt(128), 7);
          } else {
            w.f(0, 1);
          }
        }
      }
    }
  }
  if (!lossless && !allowIntrabc && s.enableCdef) {
    w.f(rng.nextInt(4), 2);
    final cdefBits = rng.nextInt(4);
    w.f(cdefBits, 2);
    final nC = 1 << cdefBits;
    for (var i = 0; i < nC; i++) {
      w.f(rng.nextInt(16), 4);
      w.f(rng.nextInt(4), 2);
      if (s.numPlanes > 1) {
        w.f(rng.nextInt(16), 4);
        w.f(rng.nextInt(4), 2);
      }
    }
  }
  if (!lossless && !allowIntrabc && s.enableRestoration) {
    var usesLr = false, usesChromaLr = false;
    for (var i = 0; i < s.numPlanes; i++) {
      final lrType = rng.nextInt(4);
      w.f(lrType, 2);
      if (lrType != 0) {
        usesLr = true;
        if (i > 0) usesChromaLr = true;
      }
    }
    if (usesLr) {
      final b1 = rng.nextInt(2);
      w.f(b1, 1);
      if (b1 != 0) w.f(rng.nextInt(2), 1);
      if (s.subsamplingX != 0 && s.subsamplingY != 0 && usesChromaLr) {
        w.f(rng.nextInt(2), 1);
      }
    }
  }
  if (!lossless) w.f(rb() ? 1 : 0, 1); // tx_mode_select
  w.f(rb() ? 1 : 0, 1); // reduced_tx_set
  if (s.filmGrainParamsPresent && (showFrame || showable)) {
    w.f(0, 1); // apply_grain = 0
  }
  return (w.toBytes(64), w.len);
}

void main() {
  tearDown(() async {
    await Simulator.reset();
  });

  const seqBytes = 32, frameBytes = 64;

  test(
    'HarborSeqHeaderParse -> HarborFrameHeaderParse compose bit-exact',
    () async {
      final sp = HarborSeqHeaderParse(maxBytes: seqBytes);
      final fp = HarborFrameHeaderParse(maxBytes: frameBytes);
      final clk = SimpleClockGenerator(10).clk;
      final reset = Logic(name: 'reset');
      final seqStart = Logic(name: 'seq_start');
      final frameStart = Logic(name: 'frame_start');
      final seqBuf = Logic(name: 'seq_buf', width: seqBytes * 8);
      final frameBuf = Logic(name: 'frame_buf', width: frameBytes * 8);

      sp.input('clk').srcConnection! <= clk;
      sp.input('reset').srcConnection! <= reset;
      sp.input('start').srcConnection! <= seqStart;
      sp.input('bytes').srcConnection! <= seqBuf;

      fp.input('clk').srcConnection! <= clk;
      fp.input('reset').srcConnection! <= reset;
      fp.input('start').srcConnection! <= frameStart;
      fp.input('bytes').srcConnection! <= frameBuf;

      // The composition: each frame-parser seq-dependency wired to the matching
      // seq-parser output.
      void wire(String frameIn, String seqOut) =>
          fp.input(frameIn).srcConnection! <= sp.output(seqOut);
      wire('seq_reduced_still_picture', 'reduced_still_picture');
      wire('seq_frame_id_numbers_present', 'frame_id_numbers_present');
      wire('seq_delta_frame_id_length_minus2', 'delta_frame_id_length_minus2');
      wire(
        'seq_additional_frame_id_length_minus1',
        'additional_frame_id_length_minus1',
      );
      wire('seq_force_screen_content_tools', 'seq_force_screen_content_tools');
      wire('seq_force_integer_mv', 'seq_force_integer_mv');
      wire('seq_order_hint_bits', 'order_hint_bits');
      wire('seq_enable_order_hint', 'enable_order_hint');
      wire('seq_decoder_model_info_present', 'decoder_model_info_present');
      wire('seq_frame_width_bits_minus1', 'frame_width_bits_minus1');
      wire('seq_frame_height_bits_minus1', 'frame_height_bits_minus1');
      wire('seq_max_frame_width_minus1', 'max_frame_width_minus1');
      wire('seq_max_frame_height_minus1', 'max_frame_height_minus1');
      wire('seq_enable_superres', 'enable_superres');
      wire('seq_use_128x128_superblock', 'use_128x128_superblock');
      wire('seq_num_planes', 'num_planes');
      wire('seq_separate_uv_delta_q', 'separate_uv_delta_q');
      wire('seq_enable_cdef', 'enable_cdef');
      wire('seq_enable_restoration', 'enable_restoration');
      wire('seq_subsampling_x', 'subsampling_x');
      wire('seq_subsampling_y', 'subsampling_y');
      wire('seq_film_grain_params_present', 'film_grain_params_present');

      await fp.build();

      reset.inject(1);
      seqStart.inject(0);
      frameStart.inject(0);
      seqBuf.inject(0);
      frameBuf.inject(0);
      Simulator.setMaxSimTime(200000000);
      unawaited(Simulator.run());
      await clk.nextPosedge;

      BigInt pack(List<int> b) {
        var v = BigInt.zero;
        for (var i = 0; i < b.length; i++) {
          v |= BigInt.from(b[i] & 0xFF) << (i * 8);
        }
        return v;
      }

      int fo(String name) => fp.output(name).value.toInt();

      final rng = Random(0x5EED);
      var sawOrderHint = false, sawCdef = false, sawScreen = false;
      for (var iter = 0; iter < 120; iter++) {
        final sbuf = _seqBytes(rng);
        final exp = _golden[iter];
        final swSeq = _Seq()
          ..seqForceScreenContentTools = exp.seqForceScreenContentTools
          ..seqForceIntegerMv = exp.seqForceIntegerMv
          ..orderHintBits = exp.orderHintBits
          ..frameWidthBitsMinus1 = exp.frameWidthBitsMinus1
          ..frameHeightBitsMinus1 = exp.frameHeightBitsMinus1
          ..enableSuperres = exp.enableSuperres
          ..numPlanes = exp.numPlanes
          ..separateUvDeltaQ = exp.separateUvDeltaQ
          ..enableCdef = exp.enableCdef
          ..enableRestoration = exp.enableRestoration
          ..subsamplingX = exp.subsamplingX
          ..subsamplingY = exp.subsamplingY
          ..filmGrainParamsPresent = exp.filmGrainParamsPresent;
        final (fbuf, fconsumed) = _frameBytes(rng, swSeq);

        if (exp.enableOrderHint) sawOrderHint = true;
        if (exp.cdefBits > 0) sawCdef = true;
        if (exp.allowScreenContentTools) sawScreen = true;

        // reset, parse the sequence header.
        reset.inject(1);
        seqBuf.inject(pack(sbuf));
        frameBuf.inject(pack(fbuf));
        await clk.nextPosedge;
        reset.inject(0);
        seqStart.inject(1);
        await clk.nextPosedge;
        seqStart.inject(0);
        var guard = 0;
        while (sp.output('done').value.toInt() != 1) {
          await clk.nextPosedge;
          if (++guard > 2000) fail('seq timeout iter=$iter');
        }
        expect(
          sp.output('unsupported').value.toInt(),
          equals(0),
          reason: 'iter=$iter seq unsupported',
        );

        // The seq outputs now hold. Parse the frame header off them.
        frameStart.inject(1);
        await clk.nextPosedge;
        frameStart.inject(0);
        guard = 0;
        while (fp.output('done').value.toInt() != 1) {
          await clk.nextPosedge;
          if (++guard > 2000) fail('frame timeout iter=$iter');
        }
        expect(
          fo('unsupported'),
          equals(0),
          reason: 'iter=$iter frame unsupported',
        );

        void chk(String name, int want, String label) =>
            expect(fo(name), equals(want), reason: 'iter=$iter $label');
        void chkB(String name, bool want, String label) =>
            expect(fo(name), equals(want ? 1 : 0), reason: 'iter=$iter $label');

        chkB('frame_is_intra', exp.frameIsIntra, 'frame_is_intra');
        chkB('show_frame', exp.showFrame, 'show_frame');
        chkB(
          'allow_screen_content_tools',
          exp.allowScreenContentTools,
          'screen',
        );
        chk('force_integer_mv', exp.forceIntegerMv, 'force_mv');
        chk('order_hint', exp.orderHint, 'order_hint');
        chk('frame_width', exp.frameWidth, 'frame_width');
        chk('frame_height', exp.frameHeight, 'frame_height');
        chk('base_q_idx', exp.baseQIdx, 'base_q');
        chkB('coded_lossless', exp.codedLossless, 'coded_lossless');
        chk('loop_filter_level_0', exp.loopFilterLevel0, 'lf_level0');
        chk('cdef_bits', exp.cdefBits, 'cdef_bits');
        chkB('uses_lr', exp.usesLr, 'uses_lr');
        chk('tx_mode', exp.txMode, 'tx_mode');
        chkB('reduced_tx_set', exp.reducedTxSet, 'reduced_tx_set');
        expect(
          fo('bits_consumed'),
          equals(fconsumed),
          reason: 'iter=$iter consumed',
        );
      }
      expect(sawOrderHint, isTrue, reason: 'no order-hint seq seen');
      expect(sawCdef, isTrue, reason: 'no cdef frame seen');
      expect(sawScreen, isTrue, reason: 'no screen-content frame seen');
      await Simulator.endSimulation();
    },
  );
}
